// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: gogo_permessage_example.proto

package gogo

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	types "github.com/gogo/protobuf/types"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type EventType int32

const (
	EventType_EVENT_TYPE_UNDEFINED EventType = 0
	EventType_EVENT_TYPE_ONE       EventType = 1
	EventType_EVENT_TYPE_TWO       EventType = 2
)

var EventType_name = map[int32]string{
	0: "EVENT_TYPE_UNDEFINED",
	1: "EVENT_TYPE_ONE",
	2: "EVENT_TYPE_TWO",
}

var EventType_value = map[string]int32{
	"EVENT_TYPE_UNDEFINED": 0,
	"EVENT_TYPE_ONE":       1,
	"EVENT_TYPE_TWO":       2,
}

func (x EventType) String() string {
	return proto.EnumName(EventType_name, int32(x))
}

func (EventType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_77954bdb6fa16f29, []int{0}
}

type TestEvent struct {
	Name      string         `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Info      string         `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	IsAwesome bool           `protobuf:"varint,3,opt,name=isAwesome,proto3" json:"isAwesome,omitempty"`
	Labels    []string       `protobuf:"bytes,4,rep,name=labels,proto3" json:"labels,omitempty"`
	Embedded  *EmbeddedEvent `protobuf:"bytes,5,opt,name=embedded,proto3" json:"embedded,omitempty"`
	// Types that are valid to be assigned to Path:
	//
	//	*TestEvent_Jedi
	//	*TestEvent_Sith
	//	*TestEvent_Other
	Path                 isTestEvent_Path     `protobuf_oneof:"path"`
	Nested               *TestEvent_NestedMsg `protobuf:"bytes,9,opt,name=nested,proto3" json:"nested,omitempty"`
	Ts                   *types.Timestamp     `protobuf:"bytes,10,opt,name=ts,proto3" json:"ts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *TestEvent) Reset()         { *m = TestEvent{} }
func (m *TestEvent) String() string { return proto.CompactTextString(m) }
func (*TestEvent) ProtoMessage()    {}
func (*TestEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_77954bdb6fa16f29, []int{0}
}
func (m *TestEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestEvent.Unmarshal(m, b)
}
func (m *TestEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestEvent.Marshal(b, m, deterministic)
}
func (m *TestEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestEvent.Merge(m, src)
}
func (m *TestEvent) XXX_Size() int {
	return xxx_messageInfo_TestEvent.Size(m)
}
func (m *TestEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_TestEvent.DiscardUnknown(m)
}

var xxx_messageInfo_TestEvent proto.InternalMessageInfo

type isTestEvent_Path interface {
	isTestEvent_Path()
}

type TestEvent_Jedi struct {
	Jedi bool `protobuf:"varint,6,opt,name=jedi,proto3,oneof" json:"jedi,omitempty"`
}
type TestEvent_Sith struct {
	Sith bool `protobuf:"varint,7,opt,name=sith,proto3,oneof" json:"sith,omitempty"`
}
type TestEvent_Other struct {
	Other string `protobuf:"bytes,8,opt,name=other,proto3,oneof" json:"other,omitempty"`
}

func (*TestEvent_Jedi) isTestEvent_Path()  {}
func (*TestEvent_Sith) isTestEvent_Path()  {}
func (*TestEvent_Other) isTestEvent_Path() {}

func (m *TestEvent) GetPath() isTestEvent_Path {
	if m != nil {
		return m.Path
	}
	return nil
}

func (m *TestEvent) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *TestEvent) GetInfo() string {
	if m != nil {
		return m.Info
	}
	return ""
}

func (m *TestEvent) GetIsAwesome() bool {
	if m != nil {
		return m.IsAwesome
	}
	return false
}

func (m *TestEvent) GetLabels() []string {
	if m != nil {
		return m.Labels
	}
	return nil
}

func (m *TestEvent) GetEmbedded() *EmbeddedEvent {
	if m != nil {
		return m.Embedded
	}
	return nil
}

func (m *TestEvent) GetJedi() bool {
	if x, ok := m.GetPath().(*TestEvent_Jedi); ok {
		return x.Jedi
	}
	return false
}

func (m *TestEvent) GetSith() bool {
	if x, ok := m.GetPath().(*TestEvent_Sith); ok {
		return x.Sith
	}
	return false
}

func (m *TestEvent) GetOther() string {
	if x, ok := m.GetPath().(*TestEvent_Other); ok {
		return x.Other
	}
	return ""
}

func (m *TestEvent) GetNested() *TestEvent_NestedMsg {
	if m != nil {
		return m.Nested
	}
	return nil
}

func (m *TestEvent) GetTs() *types.Timestamp {
	if m != nil {
		return m.Ts
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*TestEvent) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*TestEvent_Jedi)(nil),
		(*TestEvent_Sith)(nil),
		(*TestEvent_Other)(nil),
	}
}

type TestEvent_NestedMsg struct {
	Details              string   `protobuf:"bytes,1,opt,name=details,proto3" json:"details,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TestEvent_NestedMsg) Reset()         { *m = TestEvent_NestedMsg{} }
func (m *TestEvent_NestedMsg) String() string { return proto.CompactTextString(m) }
func (*TestEvent_NestedMsg) ProtoMessage()    {}
func (*TestEvent_NestedMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_77954bdb6fa16f29, []int{0, 0}
}
func (m *TestEvent_NestedMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestEvent_NestedMsg.Unmarshal(m, b)
}
func (m *TestEvent_NestedMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestEvent_NestedMsg.Marshal(b, m, deterministic)
}
func (m *TestEvent_NestedMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestEvent_NestedMsg.Merge(m, src)
}
func (m *TestEvent_NestedMsg) XXX_Size() int {
	return xxx_messageInfo_TestEvent_NestedMsg.Size(m)
}
func (m *TestEvent_NestedMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_TestEvent_NestedMsg.DiscardUnknown(m)
}

var xxx_messageInfo_TestEvent_NestedMsg proto.InternalMessageInfo

func (m *TestEvent_NestedMsg) GetDetails() string {
	if m != nil {
		return m.Details
	}
	return ""
}

type EmbeddedEvent struct {
	ID                   int32    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Stuff                string   `protobuf:"bytes,2,opt,name=stuff,proto3" json:"stuff,omitempty"`
	FavoriteNumbers      []int32  `protobuf:"varint,3,rep,packed,name=favoriteNumbers,proto3" json:"favoriteNumbers,omitempty"`
	RandomThings         [][]byte `protobuf:"bytes,4,rep,name=randomThings,proto3" json:"randomThings,omitempty"`
	Size_                int32    `protobuf:"varint,5,opt,name=Size,proto3" json:"Size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmbeddedEvent) Reset()         { *m = EmbeddedEvent{} }
func (m *EmbeddedEvent) String() string { return proto.CompactTextString(m) }
func (*EmbeddedEvent) ProtoMessage()    {}
func (*EmbeddedEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_77954bdb6fa16f29, []int{1}
}
func (m *EmbeddedEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmbeddedEvent.Unmarshal(m, b)
}
func (m *EmbeddedEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmbeddedEvent.Marshal(b, m, deterministic)
}
func (m *EmbeddedEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmbeddedEvent.Merge(m, src)
}
func (m *EmbeddedEvent) XXX_Size() int {
	return xxx_messageInfo_EmbeddedEvent.Size(m)
}
func (m *EmbeddedEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_EmbeddedEvent.DiscardUnknown(m)
}

var xxx_messageInfo_EmbeddedEvent proto.InternalMessageInfo

func (m *EmbeddedEvent) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *EmbeddedEvent) GetStuff() string {
	if m != nil {
		return m.Stuff
	}
	return ""
}

func (m *EmbeddedEvent) GetFavoriteNumbers() []int32 {
	if m != nil {
		return m.FavoriteNumbers
	}
	return nil
}

func (m *EmbeddedEvent) GetRandomThings() [][]byte {
	if m != nil {
		return m.RandomThings
	}
	return nil
}

func (m *EmbeddedEvent) GetSize_() int32 {
	if m != nil {
		return m.Size_
	}
	return 0
}

type AllTheThings struct {
	ID                   int32          `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	TheString            string         `protobuf:"bytes,2,opt,name=theString,proto3" json:"theString,omitempty"`
	TheBool              bool           `protobuf:"varint,3,opt,name=theBool,proto3" json:"theBool,omitempty"`
	TheInt32             int32          `protobuf:"varint,4,opt,name=theInt32,proto3" json:"theInt32,omitempty"`
	TheInt64             int64          `protobuf:"varint,5,opt,name=theInt64,proto3" json:"theInt64,omitempty"`
	TheUInt32            uint32         `protobuf:"varint,6,opt,name=theUInt32,proto3" json:"theUInt32,omitempty"`
	TheUInt64            uint64         `protobuf:"varint,7,opt,name=theUInt64,proto3" json:"theUInt64,omitempty"`
	TheSInt32            int32          `protobuf:"zigzag32,8,opt,name=theSInt32,proto3" json:"theSInt32,omitempty"`
	TheSInt64            int64          `protobuf:"zigzag64,9,opt,name=theSInt64,proto3" json:"theSInt64,omitempty"`
	TheFixed32           uint32         `protobuf:"fixed32,10,opt,name=theFixed32,proto3" json:"theFixed32,omitempty"`
	TheFixed64           uint64         `protobuf:"fixed64,11,opt,name=theFixed64,proto3" json:"theFixed64,omitempty"`
	TheSFixed32          int32          `protobuf:"fixed32,12,opt,name=theSFixed32,proto3" json:"theSFixed32,omitempty"`
	TheSFixed64          int64          `protobuf:"fixed64,13,opt,name=theSFixed64,proto3" json:"theSFixed64,omitempty"`
	TheFloat             float32        `protobuf:"fixed32,14,opt,name=theFloat,proto3" json:"theFloat,omitempty"`
	TheDouble            float64        `protobuf:"fixed64,15,opt,name=theDouble,proto3" json:"theDouble,omitempty"`
	TheEventType         EventType      `protobuf:"varint,16,opt,name=theEventType,proto3,enum=crowdstrike.csproto.example.permessage.gogo.EventType" json:"theEventType,omitempty"`
	TheBytes             []byte         `protobuf:"bytes,17,opt,name=theBytes,proto3" json:"theBytes,omitempty"`
	TheMessage           *EmbeddedEvent `protobuf:"bytes,18,opt,name=theMessage,proto3" json:"theMessage,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *AllTheThings) Reset()         { *m = AllTheThings{} }
func (m *AllTheThings) String() string { return proto.CompactTextString(m) }
func (*AllTheThings) ProtoMessage()    {}
func (*AllTheThings) Descriptor() ([]byte, []int) {
	return fileDescriptor_77954bdb6fa16f29, []int{2}
}
func (m *AllTheThings) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AllTheThings.Unmarshal(m, b)
}
func (m *AllTheThings) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AllTheThings.Marshal(b, m, deterministic)
}
func (m *AllTheThings) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AllTheThings.Merge(m, src)
}
func (m *AllTheThings) XXX_Size() int {
	return xxx_messageInfo_AllTheThings.Size(m)
}
func (m *AllTheThings) XXX_DiscardUnknown() {
	xxx_messageInfo_AllTheThings.DiscardUnknown(m)
}

var xxx_messageInfo_AllTheThings proto.InternalMessageInfo

func (m *AllTheThings) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *AllTheThings) GetTheString() string {
	if m != nil {
		return m.TheString
	}
	return ""
}

func (m *AllTheThings) GetTheBool() bool {
	if m != nil {
		return m.TheBool
	}
	return false
}

func (m *AllTheThings) GetTheInt32() int32 {
	if m != nil {
		return m.TheInt32
	}
	return 0
}

func (m *AllTheThings) GetTheInt64() int64 {
	if m != nil {
		return m.TheInt64
	}
	return 0
}

func (m *AllTheThings) GetTheUInt32() uint32 {
	if m != nil {
		return m.TheUInt32
	}
	return 0
}

func (m *AllTheThings) GetTheUInt64() uint64 {
	if m != nil {
		return m.TheUInt64
	}
	return 0
}

func (m *AllTheThings) GetTheSInt32() int32 {
	if m != nil {
		return m.TheSInt32
	}
	return 0
}

func (m *AllTheThings) GetTheSInt64() int64 {
	if m != nil {
		return m.TheSInt64
	}
	return 0
}

func (m *AllTheThings) GetTheFixed32() uint32 {
	if m != nil {
		return m.TheFixed32
	}
	return 0
}

func (m *AllTheThings) GetTheFixed64() uint64 {
	if m != nil {
		return m.TheFixed64
	}
	return 0
}

func (m *AllTheThings) GetTheSFixed32() int32 {
	if m != nil {
		return m.TheSFixed32
	}
	return 0
}

func (m *AllTheThings) GetTheSFixed64() int64 {
	if m != nil {
		return m.TheSFixed64
	}
	return 0
}

func (m *AllTheThings) GetTheFloat() float32 {
	if m != nil {
		return m.TheFloat
	}
	return 0
}

func (m *AllTheThings) GetTheDouble() float64 {
	if m != nil {
		return m.TheDouble
	}
	return 0
}

func (m *AllTheThings) GetTheEventType() EventType {
	if m != nil {
		return m.TheEventType
	}
	return EventType_EVENT_TYPE_UNDEFINED
}

func (m *AllTheThings) GetTheBytes() []byte {
	if m != nil {
		return m.TheBytes
	}
	return nil
}

func (m *AllTheThings) GetTheMessage() *EmbeddedEvent {
	if m != nil {
		return m.TheMessage
	}
	return nil
}

type RepeatAllTheThings struct {
	ID                   int32            `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	TheStrings           []string         `protobuf:"bytes,2,rep,name=theStrings,proto3" json:"theStrings,omitempty"`
	TheBools             []bool           `protobuf:"varint,3,rep,packed,name=theBools,proto3" json:"theBools,omitempty"`
	TheInt32S            []int32          `protobuf:"varint,4,rep,packed,name=theInt32s,proto3" json:"theInt32s,omitempty"`
	TheInt64S            []int64          `protobuf:"varint,5,rep,packed,name=theInt64s,proto3" json:"theInt64s,omitempty"`
	TheUInt32S           []uint32         `protobuf:"varint,6,rep,packed,name=theUInt32s,proto3" json:"theUInt32s,omitempty"`
	TheUInt64S           []uint64         `protobuf:"varint,7,rep,packed,name=theUInt64s,proto3" json:"theUInt64s,omitempty"`
	TheSInt32S           []int32          `protobuf:"zigzag32,8,rep,packed,name=theSInt32s,proto3" json:"theSInt32s,omitempty"`
	TheSInt64S           []int64          `protobuf:"zigzag64,9,rep,packed,name=theSInt64s,proto3" json:"theSInt64s,omitempty"`
	TheFixed32S          []uint32         `protobuf:"fixed32,10,rep,packed,name=theFixed32s,proto3" json:"theFixed32s,omitempty"`
	TheFixed64S          []uint64         `protobuf:"fixed64,11,rep,packed,name=theFixed64s,proto3" json:"theFixed64s,omitempty"`
	TheSFixed32S         []int32          `protobuf:"fixed32,12,rep,packed,name=theSFixed32s,proto3" json:"theSFixed32s,omitempty"`
	TheSFixed64S         []int64          `protobuf:"fixed64,13,rep,packed,name=theSFixed64s,proto3" json:"theSFixed64s,omitempty"`
	TheFloats            []float32        `protobuf:"fixed32,14,rep,packed,name=theFloats,proto3" json:"theFloats,omitempty"`
	TheDoubles           []float64        `protobuf:"fixed64,15,rep,packed,name=theDoubles,proto3" json:"theDoubles,omitempty"`
	TheEventTypes        []EventType      `protobuf:"varint,16,rep,packed,name=theEventTypes,proto3,enum=crowdstrike.csproto.example.permessage.gogo.EventType" json:"theEventTypes,omitempty"`
	TheBytes             [][]byte         `protobuf:"bytes,17,rep,name=theBytes,proto3" json:"theBytes,omitempty"`
	TheMessages          []*EmbeddedEvent `protobuf:"bytes,18,rep,name=theMessages,proto3" json:"theMessages,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *RepeatAllTheThings) Reset()         { *m = RepeatAllTheThings{} }
func (m *RepeatAllTheThings) String() string { return proto.CompactTextString(m) }
func (*RepeatAllTheThings) ProtoMessage()    {}
func (*RepeatAllTheThings) Descriptor() ([]byte, []int) {
	return fileDescriptor_77954bdb6fa16f29, []int{3}
}
func (m *RepeatAllTheThings) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RepeatAllTheThings.Unmarshal(m, b)
}
func (m *RepeatAllTheThings) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RepeatAllTheThings.Marshal(b, m, deterministic)
}
func (m *RepeatAllTheThings) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RepeatAllTheThings.Merge(m, src)
}
func (m *RepeatAllTheThings) XXX_Size() int {
	return xxx_messageInfo_RepeatAllTheThings.Size(m)
}
func (m *RepeatAllTheThings) XXX_DiscardUnknown() {
	xxx_messageInfo_RepeatAllTheThings.DiscardUnknown(m)
}

var xxx_messageInfo_RepeatAllTheThings proto.InternalMessageInfo

func (m *RepeatAllTheThings) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *RepeatAllTheThings) GetTheStrings() []string {
	if m != nil {
		return m.TheStrings
	}
	return nil
}

func (m *RepeatAllTheThings) GetTheBools() []bool {
	if m != nil {
		return m.TheBools
	}
	return nil
}

func (m *RepeatAllTheThings) GetTheInt32S() []int32 {
	if m != nil {
		return m.TheInt32S
	}
	return nil
}

func (m *RepeatAllTheThings) GetTheInt64S() []int64 {
	if m != nil {
		return m.TheInt64S
	}
	return nil
}

func (m *RepeatAllTheThings) GetTheUInt32S() []uint32 {
	if m != nil {
		return m.TheUInt32S
	}
	return nil
}

func (m *RepeatAllTheThings) GetTheUInt64S() []uint64 {
	if m != nil {
		return m.TheUInt64S
	}
	return nil
}

func (m *RepeatAllTheThings) GetTheSInt32S() []int32 {
	if m != nil {
		return m.TheSInt32S
	}
	return nil
}

func (m *RepeatAllTheThings) GetTheSInt64S() []int64 {
	if m != nil {
		return m.TheSInt64S
	}
	return nil
}

func (m *RepeatAllTheThings) GetTheFixed32S() []uint32 {
	if m != nil {
		return m.TheFixed32S
	}
	return nil
}

func (m *RepeatAllTheThings) GetTheFixed64S() []uint64 {
	if m != nil {
		return m.TheFixed64S
	}
	return nil
}

func (m *RepeatAllTheThings) GetTheSFixed32S() []int32 {
	if m != nil {
		return m.TheSFixed32S
	}
	return nil
}

func (m *RepeatAllTheThings) GetTheSFixed64S() []int64 {
	if m != nil {
		return m.TheSFixed64S
	}
	return nil
}

func (m *RepeatAllTheThings) GetTheFloats() []float32 {
	if m != nil {
		return m.TheFloats
	}
	return nil
}

func (m *RepeatAllTheThings) GetTheDoubles() []float64 {
	if m != nil {
		return m.TheDoubles
	}
	return nil
}

func (m *RepeatAllTheThings) GetTheEventTypes() []EventType {
	if m != nil {
		return m.TheEventTypes
	}
	return nil
}

func (m *RepeatAllTheThings) GetTheBytes() [][]byte {
	if m != nil {
		return m.TheBytes
	}
	return nil
}

func (m *RepeatAllTheThings) GetTheMessages() []*EmbeddedEvent {
	if m != nil {
		return m.TheMessages
	}
	return nil
}

type AllTheMaps struct {
	ToInt32              map[string]int32          `protobuf:"bytes,1,rep,name=toInt32,proto3" json:"toInt32,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	ToInt64              map[string]int64          `protobuf:"bytes,2,rep,name=toInt64,proto3" json:"toInt64,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	ToUInt32             map[string]uint32         `protobuf:"bytes,3,rep,name=toUInt32,proto3" json:"toUInt32,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	ToUInt64             map[string]uint64         `protobuf:"bytes,4,rep,name=toUInt64,proto3" json:"toUInt64,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	ToString             map[string]string         `protobuf:"bytes,5,rep,name=toString,proto3" json:"toString,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	ToBytes              map[string][]byte         `protobuf:"bytes,6,rep,name=toBytes,proto3" json:"toBytes,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	ToSInt32             map[string]int32          `protobuf:"bytes,7,rep,name=toSInt32,proto3" json:"toSInt32,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"zigzag32,2,opt,name=value,proto3"`
	ToSInt64             map[string]int64          `protobuf:"bytes,8,rep,name=toSInt64,proto3" json:"toSInt64,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"zigzag64,2,opt,name=value,proto3"`
	ToFixed32            map[string]uint32         `protobuf:"bytes,9,rep,name=toFixed32,proto3" json:"toFixed32,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"fixed32,2,opt,name=value,proto3"`
	ToSFixed32           map[string]int32          `protobuf:"bytes,10,rep,name=toSFixed32,proto3" json:"toSFixed32,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"fixed32,2,opt,name=value,proto3"`
	ToFixed64            map[string]uint64         `protobuf:"bytes,11,rep,name=toFixed64,proto3" json:"toFixed64,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"fixed64,2,opt,name=value,proto3"`
	ToSFixed64           map[string]int64          `protobuf:"bytes,12,rep,name=toSFixed64,proto3" json:"toSFixed64,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"fixed64,2,opt,name=value,proto3"`
	ToFloat              map[string]float32        `protobuf:"bytes,13,rep,name=toFloat,proto3" json:"toFloat,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"fixed32,2,opt,name=value,proto3"`
	ToDouble             map[string]float64        `protobuf:"bytes,14,rep,name=toDouble,proto3" json:"toDouble,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"fixed64,2,opt,name=value,proto3"`
	ToMessage            map[string]*EmbeddedEvent `protobuf:"bytes,15,rep,name=toMessage,proto3" json:"toMessage,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	ToEnum               map[string]EventType      `protobuf:"bytes,16,rep,name=toEnum,proto3" json:"toEnum,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3,enum=crowdstrike.csproto.example.permessage.gogo.EventType"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *AllTheMaps) Reset()         { *m = AllTheMaps{} }
func (m *AllTheMaps) String() string { return proto.CompactTextString(m) }
func (*AllTheMaps) ProtoMessage()    {}
func (*AllTheMaps) Descriptor() ([]byte, []int) {
	return fileDescriptor_77954bdb6fa16f29, []int{4}
}
func (m *AllTheMaps) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AllTheMaps.Unmarshal(m, b)
}
func (m *AllTheMaps) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AllTheMaps.Marshal(b, m, deterministic)
}
func (m *AllTheMaps) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AllTheMaps.Merge(m, src)
}
func (m *AllTheMaps) XXX_Size() int {
	return xxx_messageInfo_AllTheMaps.Size(m)
}
func (m *AllTheMaps) XXX_DiscardUnknown() {
	xxx_messageInfo_AllTheMaps.DiscardUnknown(m)
}

var xxx_messageInfo_AllTheMaps proto.InternalMessageInfo

func (m *AllTheMaps) GetToInt32() map[string]int32 {
	if m != nil {
		return m.ToInt32
	}
	return nil
}

func (m *AllTheMaps) GetToInt64() map[string]int64 {
	if m != nil {
		return m.ToInt64
	}
	return nil
}

func (m *AllTheMaps) GetToUInt32() map[string]uint32 {
	if m != nil {
		return m.ToUInt32
	}
	return nil
}

func (m *AllTheMaps) GetToUInt64() map[string]uint64 {
	if m != nil {
		return m.ToUInt64
	}
	return nil
}

func (m *AllTheMaps) GetToString() map[string]string {
	if m != nil {
		return m.ToString
	}
	return nil
}

func (m *AllTheMaps) GetToBytes() map[string][]byte {
	if m != nil {
		return m.ToBytes
	}
	return nil
}

func (m *AllTheMaps) GetToSInt32() map[string]int32 {
	if m != nil {
		return m.ToSInt32
	}
	return nil
}

func (m *AllTheMaps) GetToSInt64() map[string]int64 {
	if m != nil {
		return m.ToSInt64
	}
	return nil
}

func (m *AllTheMaps) GetToFixed32() map[string]uint32 {
	if m != nil {
		return m.ToFixed32
	}
	return nil
}

func (m *AllTheMaps) GetToSFixed32() map[string]int32 {
	if m != nil {
		return m.ToSFixed32
	}
	return nil
}

func (m *AllTheMaps) GetToFixed64() map[string]uint64 {
	if m != nil {
		return m.ToFixed64
	}
	return nil
}

func (m *AllTheMaps) GetToSFixed64() map[string]int64 {
	if m != nil {
		return m.ToSFixed64
	}
	return nil
}

func (m *AllTheMaps) GetToFloat() map[string]float32 {
	if m != nil {
		return m.ToFloat
	}
	return nil
}

func (m *AllTheMaps) GetToDouble() map[string]float64 {
	if m != nil {
		return m.ToDouble
	}
	return nil
}

func (m *AllTheMaps) GetToMessage() map[string]*EmbeddedEvent {
	if m != nil {
		return m.ToMessage
	}
	return nil
}

func (m *AllTheMaps) GetToEnum() map[string]EventType {
	if m != nil {
		return m.ToEnum
	}
	return nil
}

func init() {
	proto.RegisterEnum("crowdstrike.csproto.example.permessage.gogo.EventType", EventType_name, EventType_value)
	proto.RegisterType((*TestEvent)(nil), "crowdstrike.csproto.example.permessage.gogo.TestEvent")
	proto.RegisterType((*TestEvent_NestedMsg)(nil), "crowdstrike.csproto.example.permessage.gogo.TestEvent.NestedMsg")
	proto.RegisterType((*EmbeddedEvent)(nil), "crowdstrike.csproto.example.permessage.gogo.EmbeddedEvent")
	proto.RegisterType((*AllTheThings)(nil), "crowdstrike.csproto.example.permessage.gogo.AllTheThings")
	proto.RegisterType((*RepeatAllTheThings)(nil), "crowdstrike.csproto.example.permessage.gogo.RepeatAllTheThings")
	proto.RegisterType((*AllTheMaps)(nil), "crowdstrike.csproto.example.permessage.gogo.AllTheMaps")
	proto.RegisterMapType((map[string][]byte)(nil), "crowdstrike.csproto.example.permessage.gogo.AllTheMaps.ToBytesEntry")
	proto.RegisterMapType((map[string]float64)(nil), "crowdstrike.csproto.example.permessage.gogo.AllTheMaps.ToDoubleEntry")
	proto.RegisterMapType((map[string]EventType)(nil), "crowdstrike.csproto.example.permessage.gogo.AllTheMaps.ToEnumEntry")
	proto.RegisterMapType((map[string]uint32)(nil), "crowdstrike.csproto.example.permessage.gogo.AllTheMaps.ToFixed32Entry")
	proto.RegisterMapType((map[string]uint64)(nil), "crowdstrike.csproto.example.permessage.gogo.AllTheMaps.ToFixed64Entry")
	proto.RegisterMapType((map[string]float32)(nil), "crowdstrike.csproto.example.permessage.gogo.AllTheMaps.ToFloatEntry")
	proto.RegisterMapType((map[string]int32)(nil), "crowdstrike.csproto.example.permessage.gogo.AllTheMaps.ToInt32Entry")
	proto.RegisterMapType((map[string]int64)(nil), "crowdstrike.csproto.example.permessage.gogo.AllTheMaps.ToInt64Entry")
	proto.RegisterMapType((map[string]*EmbeddedEvent)(nil), "crowdstrike.csproto.example.permessage.gogo.AllTheMaps.ToMessageEntry")
	proto.RegisterMapType((map[string]int32)(nil), "crowdstrike.csproto.example.permessage.gogo.AllTheMaps.ToSFixed32Entry")
	proto.RegisterMapType((map[string]int64)(nil), "crowdstrike.csproto.example.permessage.gogo.AllTheMaps.ToSFixed64Entry")
	proto.RegisterMapType((map[string]int32)(nil), "crowdstrike.csproto.example.permessage.gogo.AllTheMaps.ToSInt32Entry")
	proto.RegisterMapType((map[string]int64)(nil), "crowdstrike.csproto.example.permessage.gogo.AllTheMaps.ToSInt64Entry")
	proto.RegisterMapType((map[string]string)(nil), "crowdstrike.csproto.example.permessage.gogo.AllTheMaps.ToStringEntry")
	proto.RegisterMapType((map[string]uint32)(nil), "crowdstrike.csproto.example.permessage.gogo.AllTheMaps.ToUInt32Entry")
	proto.RegisterMapType((map[string]uint64)(nil), "crowdstrike.csproto.example.permessage.gogo.AllTheMaps.ToUInt64Entry")
}

func init() { proto.RegisterFile("gogo_permessage_example.proto", fileDescriptor_77954bdb6fa16f29) }

var fileDescriptor_77954bdb6fa16f29 = []byte{
	// 1339 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x57, 0x6b, 0x6f, 0x1b, 0x45,
	0x14, 0xed, 0x7a, 0xfd, 0x9c, 0xf8, 0x95, 0x51, 0xa9, 0x46, 0x51, 0x81, 0x51, 0x24, 0xa4, 0x51,
	0x91, 0x6c, 0x29, 0xb5, 0x56, 0x55, 0x01, 0x89, 0xa6, 0x71, 0x68, 0x24, 0x92, 0x56, 0x13, 0xa7,
	0x40, 0xa9, 0x88, 0xd6, 0xf5, 0xc4, 0x5e, 0x6a, 0x7b, 0x8c, 0x67, 0xdc, 0x36, 0x7c, 0xe6, 0x3f,
	0xc0, 0x6f, 0xe1, 0x03, 0xbf, 0x0d, 0xcd, 0x63, 0x77, 0x67, 0x93, 0x80, 0x93, 0x6c, 0xbf, 0x79,
	0xce, 0xec, 0x39, 0xf7, 0xde, 0xb9, 0x67, 0x1e, 0x06, 0x9f, 0x8e, 0xf9, 0x98, 0x9f, 0x2e, 0xd8,
	0x72, 0xc6, 0x84, 0x08, 0xc7, 0xec, 0x94, 0x7d, 0x08, 0x67, 0x8b, 0x29, 0xeb, 0x2c, 0x96, 0x5c,
	0x72, 0xf8, 0xe5, 0x9b, 0x25, 0x7f, 0x3f, 0x12, 0x72, 0x19, 0xbd, 0x65, 0x9d, 0x37, 0x42, 0x83,
	0x9d, 0xe4, 0x93, 0x84, 0xd5, 0x51, 0x2a, 0x5b, 0x9f, 0x8f, 0x39, 0x1f, 0x4f, 0x59, 0x57, 0x7f,
	0x35, 0x5c, 0x9d, 0x75, 0x65, 0x34, 0x63, 0x42, 0x86, 0xb3, 0x85, 0x51, 0xdb, 0xfe, 0xdb, 0x07,
	0xb5, 0x01, 0x13, 0xb2, 0xff, 0x8e, 0xcd, 0x25, 0x84, 0xa0, 0x38, 0x0f, 0x67, 0x0c, 0x79, 0xd8,
	0x23, 0x35, 0xaa, 0x7f, 0x2b, 0x2c, 0x9a, 0x9f, 0x71, 0x54, 0x30, 0x98, 0xfa, 0x0d, 0xef, 0x83,
	0x5a, 0x24, 0x9e, 0xbc, 0x67, 0x82, 0xcf, 0x18, 0xf2, 0xb1, 0x47, 0xaa, 0x34, 0x05, 0xe0, 0x3d,
	0x50, 0x9e, 0x86, 0x43, 0x36, 0x15, 0xa8, 0x88, 0x7d, 0x52, 0xa3, 0x76, 0x04, 0x5f, 0x82, 0x2a,
	0x9b, 0x0d, 0xd9, 0x68, 0xc4, 0x46, 0xa8, 0x84, 0x3d, 0xb2, 0xb1, 0xf3, 0xb8, 0x73, 0x83, 0x62,
	0x3a, 0x7d, 0x4b, 0xd6, 0xb9, 0xd2, 0x44, 0x0b, 0xde, 0x05, 0xc5, 0x5f, 0xd9, 0x28, 0x42, 0x65,
	0x95, 0xc8, 0xb3, 0x3b, 0x54, 0x8f, 0x14, 0x2a, 0x22, 0x39, 0x41, 0x95, 0x18, 0x55, 0x23, 0x78,
	0x0f, 0x94, 0xb8, 0x9c, 0xb0, 0x25, 0xaa, 0xaa, 0x72, 0x9e, 0xdd, 0xa1, 0x66, 0x08, 0x7f, 0x04,
	0xe5, 0x39, 0x13, 0x92, 0x8d, 0x50, 0x4d, 0x67, 0xf6, 0xed, 0x8d, 0x32, 0x4b, 0x56, 0xb0, 0x73,
	0xa4, 0x45, 0x0e, 0xc5, 0x98, 0x5a, 0x3d, 0xf8, 0x00, 0x14, 0xa4, 0x40, 0x40, 0xab, 0x6e, 0x75,
	0x4c, 0x3f, 0x3a, 0x71, 0x3f, 0x3a, 0x83, 0xb8, 0x1f, 0xb4, 0x20, 0xc5, 0xd6, 0x17, 0xa0, 0x96,
	0x08, 0x40, 0x04, 0x2a, 0x23, 0x26, 0xc3, 0x68, 0x2a, 0x6c, 0x3f, 0xe2, 0xe1, 0x6e, 0x19, 0x14,
	0x17, 0xa1, 0x9c, 0x6c, 0xff, 0xe9, 0x81, 0x46, 0x66, 0x51, 0x60, 0x13, 0x14, 0x0e, 0xf6, 0xf4,
	0xe7, 0x25, 0x5a, 0x38, 0xd8, 0x83, 0x77, 0x41, 0x49, 0xc8, 0xd5, 0xd9, 0x99, 0xed, 0x9e, 0x19,
	0x40, 0x02, 0x5a, 0x67, 0xe1, 0x3b, 0xbe, 0x8c, 0x24, 0x3b, 0x5a, 0xcd, 0x86, 0x6c, 0x29, 0x90,
	0x8f, 0x7d, 0x52, 0xa2, 0x17, 0x61, 0xb8, 0x0d, 0xea, 0xcb, 0x70, 0x3e, 0xe2, 0xb3, 0xc1, 0x24,
	0x9a, 0x8f, 0x4d, 0x43, 0xeb, 0x34, 0x83, 0x29, 0x83, 0x1c, 0x47, 0xbf, 0x33, 0xdd, 0xd2, 0x12,
	0xd5, 0xbf, 0xb7, 0xff, 0x2a, 0x81, 0xfa, 0x93, 0xe9, 0x74, 0x30, 0x61, 0xf6, 0xa3, 0x8b, 0x89,
	0xdd, 0x07, 0x35, 0x39, 0x61, 0xc7, 0x72, 0x19, 0xcd, 0xc7, 0x36, 0xb9, 0x14, 0x50, 0xa5, 0xcb,
	0x09, 0xdb, 0xe5, 0x7c, 0x6a, 0xdd, 0x15, 0x0f, 0xe1, 0x16, 0xa8, 0xca, 0x09, 0x3b, 0x98, 0xcb,
	0x87, 0x3b, 0xa8, 0xa8, 0xd5, 0x92, 0x71, 0x3a, 0x17, 0xf4, 0x74, 0x32, 0x3e, 0x4d, 0xc6, 0x36,
	0xde, 0x89, 0x21, 0x2a, 0xa3, 0x34, 0x68, 0x0a, 0x38, 0xb3, 0x41, 0x4f, 0x1b, 0xa6, 0x48, 0x53,
	0x20, 0xce, 0xd5, 0x70, 0x95, 0x6f, 0x36, 0x69, 0x0a, 0x38, 0xb3, 0x41, 0x4f, 0x9b, 0x07, 0xd2,
	0x14, 0x80, 0x9f, 0x01, 0x20, 0x27, 0x6c, 0x3f, 0xfa, 0xc0, 0x46, 0x0f, 0x77, 0xb4, 0x0b, 0x2a,
	0xd4, 0x41, 0xdc, 0xf9, 0xa0, 0x87, 0x36, 0xb0, 0x47, 0xca, 0xd4, 0x41, 0x20, 0x06, 0x1b, 0x4a,
	0x2c, 0x16, 0xa8, 0x63, 0x8f, 0xb4, 0xa8, 0x0b, 0x65, 0xbe, 0x08, 0x7a, 0xa8, 0x81, 0x3d, 0xd2,
	0xa6, 0x2e, 0x64, 0xd7, 0x65, 0x7f, 0xca, 0x43, 0x89, 0x9a, 0xd8, 0x23, 0x05, 0x9a, 0x8c, 0x6d,
	0xf6, 0x7b, 0x7c, 0x35, 0x9c, 0x32, 0xd4, 0xc2, 0x1e, 0xf1, 0x68, 0x0a, 0xc0, 0x57, 0xa0, 0x2e,
	0x27, 0x4c, 0x5b, 0x6b, 0x70, 0xbe, 0x60, 0xa8, 0x8d, 0x3d, 0xd2, 0xdc, 0x09, 0x6e, 0xb6, 0x6b,
	0x63, 0x36, 0xcd, 0x68, 0xd9, 0xac, 0x76, 0xcf, 0x25, 0x13, 0x68, 0x13, 0x7b, 0xa4, 0x4e, 0x93,
	0x31, 0x7c, 0xa5, 0x57, 0xe5, 0xd0, 0xc8, 0x20, 0x98, 0xfb, 0xac, 0x70, 0xd4, 0xb6, 0xff, 0x29,
	0x01, 0x48, 0xd9, 0x82, 0x85, 0xf2, 0x7f, 0x0d, 0x6a, 0x1a, 0x63, 0xfc, 0x28, 0x50, 0x41, 0x1f,
	0x64, 0x0e, 0x12, 0xa7, 0xcf, 0xf9, 0xd4, 0x6c, 0x9e, 0x2a, 0x4d, 0xc6, 0x76, 0x51, 0xb5, 0x3d,
	0xcc, 0x96, 0x29, 0xd1, 0x14, 0x48, 0x67, 0x83, 0x9e, 0x40, 0x25, 0xec, 0x13, 0x9f, 0xa6, 0x80,
	0x8d, 0x7b, 0x62, 0xc9, 0x65, 0xec, 0x93, 0x06, 0x75, 0x10, 0x67, 0x5e, 0xd1, 0x2b, 0xd8, 0x27,
	0x45, 0xea, 0x20, 0x71, 0xde, 0x96, 0x5f, 0xc5, 0x3e, 0xd9, 0xa4, 0x0e, 0xe2, 0xcc, 0x2b, 0x7e,
	0x0d, 0xfb, 0x04, 0x52, 0x07, 0xb1, 0x76, 0xb2, 0xe6, 0x52, 0xe7, 0x96, 0x4f, 0x2a, 0xd4, 0x85,
	0xdc, 0x2f, 0x94, 0xc4, 0x06, 0xf6, 0x49, 0x99, 0xba, 0x90, 0x3a, 0x35, 0x1c, 0x87, 0x0a, 0x54,
	0xc7, 0x3e, 0x69, 0xd1, 0x0c, 0x96, 0xf9, 0x46, 0xc9, 0x34, 0xb0, 0x4f, 0xda, 0x34, 0x83, 0xd9,
	0x95, 0xd2, 0x46, 0x15, 0xa8, 0x89, 0x7d, 0x52, 0xa0, 0x29, 0x60, 0x2b, 0x31, 0x4e, 0x15, 0xa8,
	0x85, 0x7d, 0xe2, 0x51, 0x07, 0x81, 0xaf, 0x41, 0xc3, 0x35, 0x9c, 0x40, 0x6d, 0xec, 0xe7, 0x70,
	0x6f, 0x56, 0xec, 0x82, 0x7d, 0xfd, 0x8c, 0x7d, 0x5f, 0xeb, 0x15, 0xb2, 0x86, 0x13, 0x08, 0x62,
	0x3f, 0xa7, 0x7f, 0x5d, 0xb9, 0xed, 0x3f, 0x3e, 0x01, 0xc0, 0x58, 0xf7, 0x30, 0x5c, 0x08, 0xf8,
	0x0b, 0xa8, 0x48, 0x6e, 0xce, 0x26, 0x4f, 0x07, 0xda, 0xbb, 0x51, 0xa0, 0x54, 0xa9, 0x33, 0x30,
	0x32, 0xfd, 0xb9, 0x5c, 0x9e, 0xd3, 0x58, 0x34, 0xd1, 0x0f, 0x7a, 0x7a, 0x17, 0xe4, 0xd5, 0x0f,
	0x7a, 0xae, 0x7e, 0xd0, 0x83, 0x21, 0xa8, 0x4a, 0x6e, 0x0f, 0x66, 0x5f, 0x07, 0xe8, 0xdf, 0x3e,
	0xc0, 0x89, 0x53, 0x41, 0x22, 0x9b, 0x86, 0x08, 0x7a, 0x7a, 0x3b, 0xe6, 0x0e, 0x11, 0x17, 0x91,
	0xc8, 0x9a, 0x10, 0xf6, 0x3a, 0x2b, 0xe5, 0x0d, 0x61, 0x74, 0x92, 0x10, 0xf6, 0x52, 0xd4, 0x8d,
	0x30, 0x86, 0x2b, 0xe7, 0x6d, 0x84, 0x96, 0x49, 0x1a, 0x61, 0x5c, 0x6b, 0x4a, 0x30, 0x8d, 0xa8,
	0xe4, 0x2e, 0x21, 0xdb, 0x88, 0x63, 0xa7, 0x11, 0xf6, 0xaa, 0xac, 0x7e, 0x8c, 0x10, 0x4e, 0x23,
	0xec, 0x85, 0x3b, 0x02, 0x35, 0xc9, 0xe3, 0xeb, 0xb2, 0xa6, 0x63, 0xec, 0xdf, 0x3e, 0x86, 0x15,
	0x32, 0x41, 0x52, 0x61, 0x38, 0x06, 0x40, 0xf2, 0xe3, 0xf4, 0x5a, 0x57, 0x61, 0xbe, 0xcb, 0x51,
	0x4a, 0x26, 0x8e, 0x23, 0xed, 0x94, 0xa3, 0x9f, 0x07, 0x1f, 0xa3, 0x9c, 0x78, 0xcd, 0x52, 0x61,
	0xb7, 0x9c, 0xa0, 0xa7, 0x8f, 0xeb, 0x8f, 0x50, 0x4e, 0x1c, 0xc7, 0x91, 0x36, 0x1e, 0x36, 0x2f,
	0x91, 0x46, 0x5e, 0x0f, 0x6b, 0x99, 0xc4, 0xc3, 0xe6, 0x39, 0xa3, 0x0d, 0x66, 0x5f, 0x33, 0xcd,
	0xbc, 0x06, 0x33, 0x3a, 0x89, 0xc1, 0xec, 0x9b, 0x48, 0x77, 0x24, 0x7e, 0x9a, 0xb4, 0xf2, 0x76,
	0xc4, 0x0a, 0x25, 0x1d, 0xb1, 0x63, 0xf8, 0x33, 0x28, 0x4b, 0xde, 0x9f, 0xaf, 0x66, 0xfa, 0xd6,
	0xda, 0xd8, 0x79, 0x7a, 0xfb, 0x10, 0x4a, 0xc5, 0xe8, 0x5b, 0xc9, 0xad, 0xc7, 0xa0, 0xee, 0x9e,
	0xf5, 0xb0, 0x0d, 0xfc, 0xb7, 0xec, 0xdc, 0xfe, 0xcb, 0x50, 0x3f, 0xd5, 0xff, 0x86, 0x77, 0xe1,
	0x74, 0xc5, 0xf4, 0xd3, 0xbc, 0x44, 0xcd, 0xe0, 0x71, 0xe1, 0x91, 0x97, 0x70, 0x6d, 0x77, 0xd7,
	0x71, 0x7d, 0x97, 0xfb, 0x15, 0x68, 0x64, 0x8e, 0xe8, 0x75, 0xe4, 0xc6, 0x95, 0xe4, 0x6b, 0x46,
	0x2e, 0x5e, 0x22, 0x3b, 0xc7, 0xea, 0x3a, 0x72, 0xed, 0x52, 0xc9, 0xe9, 0x89, 0xb9, 0x8e, 0x5b,
	0xbf, 0x1c, 0xf8, 0xfa, 0x25, 0x6f, 0x5e, 0x49, 0xbe, 0x66, 0xc9, 0xd0, 0x25, 0x7f, 0x0d, 0x9a,
	0xd9, 0xf3, 0x6b, 0x1d, 0xbb, 0xe2, 0xb2, 0xbf, 0x01, 0xad, 0x0b, 0xc7, 0xd2, 0x3a, 0x7a, 0xeb,
	0xea, 0xe0, 0xd7, 0x4c, 0xbd, 0xfc, 0x1f, 0xc1, 0xaf, 0x49, 0x6f, 0x5f, 0xea, 0x57, 0x7a, 0x3a,
	0xac, 0xe3, 0x16, 0x2e, 0x2d, 0xb9, 0xb3, 0xf1, 0xd7, 0x91, 0x3d, 0x97, 0xfc, 0x41, 0x55, 0xed,
	0xee, 0xe8, 0x2b, 0xd8, 0x2f, 0x5c, 0x76, 0xbe, 0x57, 0xa1, 0x13, 0xf9, 0x37, 0xb0, 0xe1, 0x6c,
	0xf4, 0x2b, 0xc2, 0x7e, 0xef, 0x86, 0xbd, 0xfd, 0x23, 0x38, 0x0d, 0xf9, 0xe0, 0x10, 0xd4, 0xd2,
	0x3f, 0x73, 0x08, 0xdc, 0xed, 0xbf, 0xec, 0x1f, 0x0d, 0x4e, 0x07, 0x3f, 0xbd, 0xe8, 0x9f, 0x9e,
	0x1c, 0xed, 0xf5, 0xf7, 0x0f, 0x8e, 0xfa, 0x7b, 0xed, 0x3b, 0x10, 0x82, 0xa6, 0x33, 0xf3, 0xfc,
	0xa8, 0xdf, 0xf6, 0x2e, 0x60, 0x83, 0x1f, 0x9e, 0xb7, 0x0b, 0xbb, 0x8f, 0x5e, 0x05, 0xe3, 0x48,
	0x4e, 0x56, 0xc3, 0xce, 0x1b, 0x3e, 0xeb, 0x3e, 0x55, 0xd9, 0x1d, 0xeb, 0xec, 0xba, 0x36, 0xbb,
	0xae, 0xcd, 0xae, 0x9b, 0x66, 0xd7, 0x55, 0xd9, 0x0d, 0xcb, 0x7a, 0xfa, 0xe1, 0xbf, 0x01, 0x00,
	0x00, 0xff, 0xff, 0x50, 0xc3, 0xeb, 0x5f, 0x38, 0x13, 0x00, 0x00,
}
