// GENERATED CODE - DO NOT EDIT
// This file was generated by protoc-gen-fastmarshal

package googlev2

import (
	"fmt"
	"strings"
	"github.com/CrowdStrike/csproto"
)

//------------------------------------------------------------------------------
// Custom Protobuf size/marshal/unmarshal code for BaseEvent

// Size calculates and returns the size, in bytes, required to hold the contents of m using the Protobuf
// binary encoding.
func (m *BaseEvent) Size() int {
	if m == nil {
		return 0
	}
	var sz, l int
	_ = l // avoid unused variable

	// EventID (string,required)
	if m.EventID != nil {
		l = len(*m.EventID)
		sz += csproto.SizeOfTagKey(1) + csproto.SizeOfVarint(uint64(l)) + l
	}
	// SourceID (string,required)
	if m.SourceID != nil {
		l = len(*m.SourceID)
		sz += csproto.SizeOfTagKey(2) + csproto.SizeOfVarint(uint64(l)) + l
	}
	// Timestamp (uint64,required)
	if m.Timestamp != nil {
		sz += csproto.SizeOfTagKey(3) + csproto.SizeOfVarint(uint64(*m.Timestamp))
	}
	// EventType (enum,required)
	if m.EventType != nil {
		sz += csproto.SizeOfTagKey(4) + csproto.SizeOfVarint(uint64(*m.EventType))
	}
	// Data (bytes,optional)
	l = len(m.Data)
	sz += csproto.SizeOfTagKey(5) + csproto.SizeOfVarint(uint64(l)) + l
	// extension field - eventExt (message,optional)
	if extVal, _ := csproto.GetExtension(m, E_TestEvent_EventExt); extVal != nil {
		l = csproto.Size(extVal)
		sz += csproto.SizeOfTagKey(100) + csproto.SizeOfVarint(uint64(l)) + l
	}

	return sz
}

// Marshal converts the contents of m to the Protobuf binary encoding and returns the result or an error.
func (m *BaseEvent) Marshal() ([]byte, error) {
	siz := m.Size()
	buf := make([]byte, siz)
	err := m.MarshalTo(buf)
	return buf, err
}

// MarshalTo converts the contents of m to the Protobuf binary encoding and writes the result to dest.
func (m *BaseEvent) MarshalTo(dest []byte) error {
	var (
		enc    = csproto.NewEncoder(dest)
		buf    []byte
		err    error
		extVal interface{}
	)
	// ensure no unused variables
	_ = enc
	_ = buf
	_ = err
	_ = extVal

	// EventID (1,string,required)
	if m.EventID == nil {
		return fmt.Errorf("required field 'EventID' has no value")
	}
	enc.EncodeString(1, *m.EventID)
	// SourceID (2,string,required)
	if m.SourceID == nil {
		return fmt.Errorf("required field 'SourceID' has no value")
	}
	enc.EncodeString(2, *m.SourceID)
	// Timestamp (3,uint64,required)
	if m.Timestamp == nil {
		return fmt.Errorf("required field 'Timestamp' has no value")
	}
	enc.EncodeUInt64(3, *m.Timestamp)
	// EventType (4,enum,required)
	if m.EventType == nil {
		return fmt.Errorf("required field 'EventType' has no value")
	}
	enc.EncodeInt32(4, int32(*m.EventType))
	// Data (5,bytes,optional)
	enc.EncodeBytes(5, m.Data)

	// extension field - eventExt (message,optional)
	if extVal, _ = csproto.GetExtension(m, E_TestEvent_EventExt); extVal != nil {
		if err = enc.EncodeNested(100, extVal); err != nil {
			return fmt.Errorf("unable to encode message data for extension field 'eventExt' (tag=100): %w", err)
		}
	}

	return nil
}

// Unmarshal decodes a binary encoded Protobuf message from p and populates m with the result.
func (m *BaseEvent) Unmarshal(p []byte) error {
	if len(p) == 0 {
		return fmt.Errorf("cannot unmarshal from an empty buffer")
	}
	// clear any existing data
	m.Reset()
	dec := csproto.NewDecoder(p)
	for dec.More() {
		tag, wt, err := dec.DecodeTag()
		if err != nil {
			return err
		}
		switch tag {
		case 1: // EventID (string,required)
			if wt != csproto.WireTypeLengthDelimited {
				return fmt.Errorf("incorrect wire type %v for field 'eventID' (tag=1), expected 2 (length-delimited)", wt)
			}
			if s, err := dec.DecodeString(); err != nil {
				return fmt.Errorf("unable to decode string value for field 'eventID' (tag=1): %w", err)
			} else {
				m.EventID = csproto.String(s)
			}

		case 2: // SourceID (string,required)
			if wt != csproto.WireTypeLengthDelimited {
				return fmt.Errorf("incorrect wire type %v for field 'sourceID' (tag=2), expected 2 (length-delimited)", wt)
			}
			if s, err := dec.DecodeString(); err != nil {
				return fmt.Errorf("unable to decode string value for field 'sourceID' (tag=2): %w", err)
			} else {
				m.SourceID = csproto.String(s)
			}

		case 3: // Timestamp (uint64,required)
			if wt != csproto.WireTypeVarint {
				return fmt.Errorf("incorrect wire type %v for tag field 'timestamp' (tag=3), expected 0 (varint)", wt)
			}
			if v, err := dec.DecodeUInt64(); err != nil {
				return fmt.Errorf("unable to decode uint64 value for field 'timestamp' (tag=3): %w", err)
			} else {
				m.Timestamp = csproto.Uint64(v)
			}
		case 4: // EventType (enum,required)
			if wt != csproto.WireTypeVarint {
				return fmt.Errorf("incorrect wire type %v for tag field 'eventType' (tag=4), expected 0 (varint)", wt)
			}
			if v, err := dec.DecodeInt32(); err != nil {
				return fmt.Errorf("unable to decode int32 enum value for field 'eventType' (tag=4): %w", err)
			} else {
				ev := EventType(v)
				m.EventType = &ev
			}
		case 5: // Data (bytes,optional)

			if wt != csproto.WireTypeLengthDelimited {
				return fmt.Errorf("incorrect wire type %v for field 'data' (tag=5), expected 2 (length-delimited)", wt)
			}
			if b, err := dec.DecodeBytes(); err != nil {
				return fmt.Errorf("unable to decode bytes value for field 'data' (tag=5): %w", err)
			} else {
				m.Data = b
			}

		case 100: // eventExt (extension,message)
			var mm_eventExt TestEvent
			if err := dec.DecodeNested(&mm_eventExt); err != nil {
				return fmt.Errorf("unable to decode message field 'eventExt' (tag=100): %w", err)
			} else {
				if err = csproto.SetExtension(m, E_TestEvent_EventExt, &mm_eventExt); err != nil {
					return fmt.Errorf("unable to set extension field 'eventExt' (tag=100): %w", err)
				}
			}
		default:
			if skipped, err := dec.Skip(tag, wt); err != nil {
				return fmt.Errorf("invalid operation skipping tag %v: %w", tag, err)
			} else {
				m.unknownFields = append(m.unknownFields, skipped...)
			}
		}
	}
	// verify required fields are assigned
	if err := m.csprotoCheckRequiredFields(); err != nil {
		return err
	}

	return nil
}

// csprotoCheckRequiredFields is called by Unmarshal() to ensure that all required fields have been
// populated.
func (m *BaseEvent) csprotoCheckRequiredFields() error {
	var missingFields []string

	if m.EventID == nil {
		missingFields = append(missingFields, "EventID")
	}
	if m.SourceID == nil {
		missingFields = append(missingFields, "SourceID")
	}
	if m.Timestamp == nil {
		missingFields = append(missingFields, "Timestamp")
	}
	if m.EventType == nil {
		missingFields = append(missingFields, "EventType")
	}

	if len(missingFields) > 0 {
		var sb strings.Builder
		sb.WriteString("cannot unmarshal, one or more required fields missing: ")
		for i, s := range missingFields {
			if i > 0 {
				sb.WriteRune(',')
			}
			sb.WriteString(s)
		}
		return fmt.Errorf(sb.String())
	}
	return nil
}

//------------------------------------------------------------------------------
// Custom Protobuf size/marshal/unmarshal code for TestEvent

// Size calculates and returns the size, in bytes, required to hold the contents of m using the Protobuf
// binary encoding.
func (m *TestEvent) Size() int {
	if m == nil {
		return 0
	}
	var sz, l int
	_ = l // avoid unused variable

	// Name (string,optional)
	if m.Name != nil {
		l = len(*m.Name)
		sz += csproto.SizeOfTagKey(1) + csproto.SizeOfVarint(uint64(l)) + l
	}
	// Info (string,optional)
	if m.Info != nil {
		l = len(*m.Info)
		sz += csproto.SizeOfTagKey(2) + csproto.SizeOfVarint(uint64(l)) + l
	}
	// IsAwesome (bool,optional)
	if m.IsAwesome != nil {
		sz += csproto.SizeOfTagKey(3) + 1
	}
	// Labels (string,repeated)
	for _, sv := range m.Labels {
		l = len(sv)
		sz += csproto.SizeOfTagKey(4) + csproto.SizeOfVarint(uint64(l)) + l
	}
	// Embedded (message,required)
	if m.Embedded != nil {
		l = csproto.Size(m.Embedded)
		sz += csproto.SizeOfTagKey(5) + csproto.SizeOfVarint(uint64(l)) + l
	}
	// Nested (message,optional)
	if m.Nested != nil {
		l = csproto.Size(m.Nested)
		sz += csproto.SizeOfTagKey(9) + csproto.SizeOfVarint(uint64(l)) + l
	}
	// Path (oneof)
	if m.Path != nil {
		switch typedVal := m.Path.(type) {
		case *TestEvent_Jedi: // jedi (6,bool)
			sz += csproto.SizeOfTagKey(6) + 1
		case *TestEvent_Sith: // sith (7,bool)
			sz += csproto.SizeOfTagKey(7) + 1
		case *TestEvent_Other: // other (8,string)
			l = len(typedVal.Other)
			sz += csproto.SizeOfTagKey(8) + csproto.SizeOfVarint(uint64(l)) + l
		default:
			_ = typedVal // ensure no unused variable
		}
	}

	return sz
}

// Marshal converts the contents of m to the Protobuf binary encoding and returns the result or an error.
func (m *TestEvent) Marshal() ([]byte, error) {
	siz := m.Size()
	buf := make([]byte, siz)
	err := m.MarshalTo(buf)
	return buf, err
}

// MarshalTo converts the contents of m to the Protobuf binary encoding and writes the result to dest.
func (m *TestEvent) MarshalTo(dest []byte) error {
	var (
		enc    = csproto.NewEncoder(dest)
		buf    []byte
		err    error
		extVal interface{}
	)
	// ensure no unused variables
	_ = enc
	_ = buf
	_ = err
	_ = extVal

	// Name (1,string,optional)
	if m.Name != nil {
		enc.EncodeString(1, *m.Name)
	}
	// Info (2,string,optional)
	if m.Info != nil {
		enc.EncodeString(2, *m.Info)
	}
	// IsAwesome (3,bool,optional)
	if m.IsAwesome != nil {
		enc.EncodeBool(3, *m.IsAwesome)
	}
	// Labels (4,string,repeated)
	for _, val := range m.Labels {
		enc.EncodeString(4, val)
	}
	// Embedded (5,message,required)
	if m.Embedded == nil {
		return fmt.Errorf("required field 'Embedded' has no value")
	}
	if err = enc.EncodeNested(5, m.Embedded); err != nil {
		return fmt.Errorf("unable to encode message data for field 'embedded' (tag=5): %w", err)
	}
	// Nested (9,message,optional)
	if m.Nested != nil {
		if err = enc.EncodeNested(9, m.Nested); err != nil {
			return fmt.Errorf("unable to encode message data for field 'nested' (tag=9): %w", err)
		}
	}
	// Path (oneof)
	if m.Path != nil {
		switch typedVal := m.Path.(type) {
		case *TestEvent_Jedi: // jedi (6,bool)
			enc.EncodeBool(6, typedVal.Jedi)
		case *TestEvent_Sith: // sith (7,bool)
			enc.EncodeBool(7, typedVal.Sith)
		case *TestEvent_Other: // other (8,string)
			enc.EncodeString(8, typedVal.Other)
		default:
			_ = typedVal // ensure no unused variable
		}
	}
	return nil
}

// Unmarshal decodes a binary encoded Protobuf message from p and populates m with the result.
func (m *TestEvent) Unmarshal(p []byte) error {
	if len(p) == 0 {
		return fmt.Errorf("cannot unmarshal from an empty buffer")
	}
	// clear any existing data
	m.Reset()
	dec := csproto.NewDecoder(p)
	for dec.More() {
		tag, wt, err := dec.DecodeTag()
		if err != nil {
			return err
		}
		switch tag {
		case 1: // Name (string,optional)
			if wt != csproto.WireTypeLengthDelimited {
				return fmt.Errorf("incorrect wire type %v for field 'name' (tag=1), expected 2 (length-delimited)", wt)
			}
			if s, err := dec.DecodeString(); err != nil {
				return fmt.Errorf("unable to decode string value for field 'name' (tag=1): %w", err)
			} else {
				m.Name = csproto.String(s)
			}

		case 2: // Info (string,optional)
			if wt != csproto.WireTypeLengthDelimited {
				return fmt.Errorf("incorrect wire type %v for field 'info' (tag=2), expected 2 (length-delimited)", wt)
			}
			if s, err := dec.DecodeString(); err != nil {
				return fmt.Errorf("unable to decode string value for field 'info' (tag=2): %w", err)
			} else {
				m.Info = csproto.String(s)
			}

		case 3: // IsAwesome (bool,optional)
			if wt != csproto.WireTypeVarint {
				return fmt.Errorf("incorrect wire type %v for tag field 'isAwesome' (tag=3), expected 0 (varint)", wt)
			}
			if v, err := dec.DecodeBool(); err != nil {
				return fmt.Errorf("unable to decode boolean value for field 'isAwesome' (tag=3): %w", err)
			} else {
				m.IsAwesome = csproto.Bool(v)
			}
		case 4: // Labels (string,repeated)
			if wt != csproto.WireTypeLengthDelimited {
				return fmt.Errorf("incorrect wire type %v for field 'labels' (tag=4), expected 2 (length-delimited)", wt)
			}
			if s, err := dec.DecodeString(); err != nil {
				return fmt.Errorf("unable to decode string value for field 'labels' (tag=4): %w", err)
			} else {
				m.Labels = append(m.Labels, s)
			}

		case 5: // Embedded (message,required)
			if wt != csproto.WireTypeLengthDelimited {
				return fmt.Errorf("incorrect wire type %v for field 'embedded' (tag=5), expected 2 (length-delimited)", wt)
			}
			var mm EmbeddedEvent
			if err = dec.DecodeNested(&mm); err != nil {
				return fmt.Errorf("unable to decode message value for field 'embedded' (tag=5): %w", err)
			}
			m.Embedded = &mm

		case 9: // Nested (message,optional)
			if wt != csproto.WireTypeLengthDelimited {
				return fmt.Errorf("incorrect wire type %v for field 'nested' (tag=9), expected 2 (length-delimited)", wt)
			}
			var mm TestEvent_NestedMsg
			if err = dec.DecodeNested(&mm); err != nil {
				return fmt.Errorf("unable to decode message value for field 'nested' (tag=9): %w", err)
			}
			m.Nested = &mm

		case 6: // path.jedi (oneof,bool)
			var ov TestEvent_Jedi
			if wt != csproto.WireTypeVarint {
				return fmt.Errorf("incorrect wire type %v for tag field 'jedi' (tag=6), expected 0 (varint)", wt)
			}
			if v, err := dec.DecodeBool(); err != nil {
				return fmt.Errorf("unable to decode boolean value for field 'jedi' (tag=6): %w", err)
			} else {
				ov.Jedi = v
			}
			m.Path = &ov
		case 7: // path.sith (oneof,bool)
			var ov TestEvent_Sith
			if wt != csproto.WireTypeVarint {
				return fmt.Errorf("incorrect wire type %v for tag field 'sith' (tag=7), expected 0 (varint)", wt)
			}
			if v, err := dec.DecodeBool(); err != nil {
				return fmt.Errorf("unable to decode boolean value for field 'sith' (tag=7): %w", err)
			} else {
				ov.Sith = v
			}
			m.Path = &ov
		case 8: // path.other (oneof,string)
			var ov TestEvent_Other
			if wt != csproto.WireTypeLengthDelimited {
				return fmt.Errorf("incorrect wire type %v for tag field 'other' (tag=8), expected 2 (length-delimited)", wt)
			}
			if s, err := dec.DecodeString(); err != nil {
				return fmt.Errorf("unable to decode string value for field 'other' (tag=8): %w", err)
			} else {
				ov.Other = s
			}
			m.Path = &ov
		default:
			if skipped, err := dec.Skip(tag, wt); err != nil {
				return fmt.Errorf("invalid operation skipping tag %v: %w", tag, err)
			} else {
				m.unknownFields = append(m.unknownFields, skipped...)
			}
		}
	}
	// verify required fields are assigned
	if err := m.csprotoCheckRequiredFields(); err != nil {
		return err
	}

	return nil
}

// csprotoCheckRequiredFields is called by Unmarshal() to ensure that all required fields have been
// populated.
func (m *TestEvent) csprotoCheckRequiredFields() error {
	var missingFields []string

	if m.Embedded == nil {
		missingFields = append(missingFields, "Embedded")
	}

	if len(missingFields) > 0 {
		var sb strings.Builder
		sb.WriteString("cannot unmarshal, one or more required fields missing: ")
		for i, s := range missingFields {
			if i > 0 {
				sb.WriteRune(',')
			}
			sb.WriteString(s)
		}
		return fmt.Errorf(sb.String())
	}
	return nil
}

//------------------------------------------------------------------------------
// Custom Protobuf size/marshal/unmarshal code for EmbeddedEvent

// Size calculates and returns the size, in bytes, required to hold the contents of m using the Protobuf
// binary encoding.
func (m *EmbeddedEvent) Size() int {
	if m == nil {
		return 0
	}
	var sz, l int
	_ = l // avoid unused variable

	// ID (int32,required)
	if m.ID != nil {
		sz += csproto.SizeOfTagKey(1) + csproto.SizeOfVarint(uint64(*m.ID))
	}
	// Stuff (string,optional)
	if m.Stuff != nil {
		l = len(*m.Stuff)
		sz += csproto.SizeOfTagKey(2) + csproto.SizeOfVarint(uint64(l)) + l
	}
	// FavoriteNumbers (int32,repeated)
	for _, iv := range m.FavoriteNumbers {
		sz += csproto.SizeOfTagKey(3) + csproto.SizeOfVarint(uint64(iv))
	}
	// RandomThings (bytes,repeated)
	for _, bv := range m.RandomThings {
		if l = len(bv); l > 0 {
			sz += csproto.SizeOfTagKey(4) + csproto.SizeOfVarint(uint64(l)) + l
		}
	}
	return sz
}

// Marshal converts the contents of m to the Protobuf binary encoding and returns the result or an error.
func (m *EmbeddedEvent) Marshal() ([]byte, error) {
	siz := m.Size()
	buf := make([]byte, siz)
	err := m.MarshalTo(buf)
	return buf, err
}

// MarshalTo converts the contents of m to the Protobuf binary encoding and writes the result to dest.
func (m *EmbeddedEvent) MarshalTo(dest []byte) error {
	var (
		enc    = csproto.NewEncoder(dest)
		buf    []byte
		err    error
		extVal interface{}
	)
	// ensure no unused variables
	_ = enc
	_ = buf
	_ = err
	_ = extVal

	// ID (1,int32,required)
	if m.ID == nil {
		return fmt.Errorf("required field 'ID' has no value")
	}
	enc.EncodeInt32(1, *m.ID)
	// Stuff (2,string,optional)
	if m.Stuff != nil {
		enc.EncodeString(2, *m.Stuff)
	}
	// FavoriteNumbers (3,int32,repeated)
	for _, val := range m.FavoriteNumbers {
		enc.EncodeInt32(3, val)
	}
	// RandomThings (4,bytes,repeated)
	for _, val := range m.RandomThings {
		enc.EncodeBytes(4, val)
	}
	return nil
}

// Unmarshal decodes a binary encoded Protobuf message from p and populates m with the result.
func (m *EmbeddedEvent) Unmarshal(p []byte) error {
	if len(p) == 0 {
		return fmt.Errorf("cannot unmarshal from an empty buffer")
	}
	// clear any existing data
	m.Reset()
	dec := csproto.NewDecoder(p)
	for dec.More() {
		tag, wt, err := dec.DecodeTag()
		if err != nil {
			return err
		}
		switch tag {
		case 1: // ID (int32,required)
			if wt != csproto.WireTypeVarint {
				return fmt.Errorf("incorrect wire type %v for tag field 'ID' (tag=1), expected 0 (varint)", wt)
			}
			if v, err := dec.DecodeInt32(); err != nil {
				return fmt.Errorf("unable to decode int32 value for field 'ID' (tag=1): %w", err)
			} else {
				m.ID = csproto.Int32(v)
			}
		case 2: // Stuff (string,optional)
			if wt != csproto.WireTypeLengthDelimited {
				return fmt.Errorf("incorrect wire type %v for field 'stuff' (tag=2), expected 2 (length-delimited)", wt)
			}
			if s, err := dec.DecodeString(); err != nil {
				return fmt.Errorf("unable to decode string value for field 'stuff' (tag=2): %w", err)
			} else {
				m.Stuff = csproto.String(s)
			}

		case 3: // FavoriteNumbers (int32,repeated)
			switch wt {
			case csproto.WireTypeVarint:
				if v, err := dec.DecodeInt32(); err != nil {
					return fmt.Errorf("unable to decode int32 value for field 'favoriteNumbers' (tag=3): %w", err)
				} else {
					m.FavoriteNumbers = append(m.FavoriteNumbers, v)
				}
			case csproto.WireTypeLengthDelimited:
				if v, err := dec.DecodePackedInt32(); err != nil {
					return fmt.Errorf("unable to decode packed int32 values for field 'favoriteNumbers' (tag=3): %w", err)
				} else {
					m.FavoriteNumbers = append(m.FavoriteNumbers, v...)
				}
			default:
				return fmt.Errorf("incorrect wire type %v for repeated field 'favoriteNumbers' (tag=3), expected 0 (varint) or 1 (length-delimited)", wt)
			}
		case 4: // RandomThings (bytes,repeated)

			if wt != csproto.WireTypeLengthDelimited {
				return fmt.Errorf("incorrect wire type %v for field 'randomThings' (tag=4), expected 2 (length-delimited)", wt)
			}
			if b, err := dec.DecodeBytes(); err != nil {
				return fmt.Errorf("unable to decode bytes value for field 'randomThings' (tag=4): %w", err)
			} else {
				m.RandomThings = append(m.RandomThings, b)
			}

		default:
			if skipped, err := dec.Skip(tag, wt); err != nil {
				return fmt.Errorf("invalid operation skipping tag %v: %w", tag, err)
			} else {
				m.unknownFields = append(m.unknownFields, skipped...)
			}
		}
	}
	// verify required fields are assigned
	if err := m.csprotoCheckRequiredFields(); err != nil {
		return err
	}

	return nil
}

// csprotoCheckRequiredFields is called by Unmarshal() to ensure that all required fields have been
// populated.
func (m *EmbeddedEvent) csprotoCheckRequiredFields() error {
	var missingFields []string

	if m.ID == nil {
		missingFields = append(missingFields, "ID")
	}

	if len(missingFields) > 0 {
		var sb strings.Builder
		sb.WriteString("cannot unmarshal, one or more required fields missing: ")
		for i, s := range missingFields {
			if i > 0 {
				sb.WriteRune(',')
			}
			sb.WriteString(s)
		}
		return fmt.Errorf(sb.String())
	}
	return nil
}

//------------------------------------------------------------------------------
// Custom Protobuf size/marshal/unmarshal code for AllTheThings

// Size calculates and returns the size, in bytes, required to hold the contents of m using the Protobuf
// binary encoding.
func (m *AllTheThings) Size() int {
	if m == nil {
		return 0
	}
	var sz, l int
	_ = l // avoid unused variable

	// ID (int32,required)
	if m.ID != nil {
		sz += csproto.SizeOfTagKey(1) + csproto.SizeOfVarint(uint64(*m.ID))
	}
	// TheString (string,optional)
	if m.TheString != nil {
		l = len(*m.TheString)
		sz += csproto.SizeOfTagKey(2) + csproto.SizeOfVarint(uint64(l)) + l
	}
	// TheBool (bool,optional)
	if m.TheBool != nil {
		sz += csproto.SizeOfTagKey(3) + 1
	}
	// TheInt32 (int32,optional)
	if m.TheInt32 != nil {
		sz += csproto.SizeOfTagKey(4) + csproto.SizeOfVarint(uint64(*m.TheInt32))
	}
	// TheInt64 (int64,optional)
	if m.TheInt64 != nil {
		sz += csproto.SizeOfTagKey(5) + csproto.SizeOfVarint(uint64(*m.TheInt64))
	}
	// TheUInt32 (uint32,optional)
	if m.TheUInt32 != nil {
		sz += csproto.SizeOfTagKey(6) + csproto.SizeOfVarint(uint64(*m.TheUInt32))
	}
	// TheUInt64 (uint64,optional)
	if m.TheUInt64 != nil {
		sz += csproto.SizeOfTagKey(7) + csproto.SizeOfVarint(uint64(*m.TheUInt64))
	}
	// TheSInt32 (sint32,optional)
	if m.TheSInt32 != nil {
		sz += csproto.SizeOfTagKey(8) + csproto.SizeOfZigZag(uint64(*m.TheSInt32))
	}
	// TheSInt64 (sint64,optional)
	if m.TheSInt64 != nil {
		sz += csproto.SizeOfTagKey(9) + csproto.SizeOfZigZag(uint64(*m.TheSInt64))
	}
	// TheFixed32 (fixed32,optional)
	if m.TheFixed32 != nil {
		sz += csproto.SizeOfTagKey(10) + 4
	}
	// TheFixed64 (fixed64,optional)
	if m.TheFixed64 != nil {
		sz += csproto.SizeOfTagKey(11) + 8
	}
	// TheSFixed32 (sfixed32,optional)
	if m.TheSFixed32 != nil {
		sz += csproto.SizeOfTagKey(12) + 4
	}
	// TheSFixed64 (sfixed64,optional)
	if m.TheSFixed64 != nil {
		sz += csproto.SizeOfTagKey(13) + 8
	}
	// TheFloat (float,optional)
	if m.TheFloat != nil {
		sz += csproto.SizeOfTagKey(14) + 4
	}
	// TheDouble (double,optional)
	if m.TheDouble != nil {
		sz += csproto.SizeOfTagKey(15) + 8
	}
	// TheEventType (enum,optional)
	if m.TheEventType != nil {
		sz += csproto.SizeOfTagKey(16) + csproto.SizeOfVarint(uint64(*m.TheEventType))
	}
	// TheBytes (bytes,optional)
	l = len(m.TheBytes)
	sz += csproto.SizeOfTagKey(17) + csproto.SizeOfVarint(uint64(l)) + l
	// TheMessage (message,optional)
	if m.TheMessage != nil {
		l = csproto.Size(m.TheMessage)
		sz += csproto.SizeOfTagKey(18) + csproto.SizeOfVarint(uint64(l)) + l
	}
	return sz
}

// Marshal converts the contents of m to the Protobuf binary encoding and returns the result or an error.
func (m *AllTheThings) Marshal() ([]byte, error) {
	siz := m.Size()
	buf := make([]byte, siz)
	err := m.MarshalTo(buf)
	return buf, err
}

// MarshalTo converts the contents of m to the Protobuf binary encoding and writes the result to dest.
func (m *AllTheThings) MarshalTo(dest []byte) error {
	var (
		enc    = csproto.NewEncoder(dest)
		buf    []byte
		err    error
		extVal interface{}
	)
	// ensure no unused variables
	_ = enc
	_ = buf
	_ = err
	_ = extVal

	// ID (1,int32,required)
	if m.ID == nil {
		return fmt.Errorf("required field 'ID' has no value")
	}
	enc.EncodeInt32(1, *m.ID)
	// TheString (2,string,optional)
	if m.TheString != nil {
		enc.EncodeString(2, *m.TheString)
	}
	// TheBool (3,bool,optional)
	if m.TheBool != nil {
		enc.EncodeBool(3, *m.TheBool)
	}
	// TheInt32 (4,int32,optional)
	if m.TheInt32 != nil {
		enc.EncodeInt32(4, *m.TheInt32)
	}
	// TheInt64 (5,int64,optional)
	if m.TheInt64 != nil {
		enc.EncodeInt64(5, *m.TheInt64)
	}
	// TheUInt32 (6,uint32,optional)
	if m.TheUInt32 != nil {
		enc.EncodeUInt32(6, *m.TheUInt32)
	}
	// TheUInt64 (7,uint64,optional)
	if m.TheUInt64 != nil {
		enc.EncodeUInt64(7, *m.TheUInt64)
	}
	// TheSInt32 (8,sint32,optional)
	if m.TheSInt32 != nil {
		enc.EncodeSInt32(8, *m.TheSInt32)
	}
	// TheSInt64 (9,sint64,optional)
	if m.TheSInt64 != nil {
		enc.EncodeSInt64(9, *m.TheSInt64)
	}
	// TheFixed32 (10,fixed32,optional)
	if m.TheFixed32 != nil {
		enc.EncodeFixed32(10, *m.TheFixed32)
	}
	// TheFixed64 (11,fixed64,optional)
	if m.TheFixed64 != nil {
		enc.EncodeFixed64(11, *m.TheFixed64)
	}
	// TheSFixed32 (12,sfixed32,optional)
	if m.TheSFixed32 != nil {
		enc.EncodeFixed32(12, uint32(*m.TheSFixed32))
	}
	// TheSFixed64 (13,sfixed64,optional)
	if m.TheSFixed64 != nil {
		enc.EncodeFixed64(13, uint64(*m.TheSFixed64))
	}
	// TheFloat (14,float,optional)
	if m.TheFloat != nil {
		enc.EncodeFloat32(14, *m.TheFloat)
	}
	// TheDouble (15,double,optional)
	if m.TheDouble != nil {
		enc.EncodeFloat64(15, *m.TheDouble)
	}
	// TheEventType (16,enum,optional)
	if m.TheEventType != nil {
		enc.EncodeInt32(16, int32(*m.TheEventType))
	}
	// TheBytes (17,bytes,optional)
	enc.EncodeBytes(17, m.TheBytes)
	// TheMessage (18,message,optional)
	if m.TheMessage != nil {
		if err = enc.EncodeNested(18, m.TheMessage); err != nil {
			return fmt.Errorf("unable to encode message data for field 'theMessage' (tag=18): %w", err)
		}
	}
	return nil
}

// Unmarshal decodes a binary encoded Protobuf message from p and populates m with the result.
func (m *AllTheThings) Unmarshal(p []byte) error {
	if len(p) == 0 {
		return fmt.Errorf("cannot unmarshal from an empty buffer")
	}
	// clear any existing data
	m.Reset()
	dec := csproto.NewDecoder(p)
	for dec.More() {
		tag, wt, err := dec.DecodeTag()
		if err != nil {
			return err
		}
		switch tag {
		case 1: // ID (int32,required)
			if wt != csproto.WireTypeVarint {
				return fmt.Errorf("incorrect wire type %v for tag field 'ID' (tag=1), expected 0 (varint)", wt)
			}
			if v, err := dec.DecodeInt32(); err != nil {
				return fmt.Errorf("unable to decode int32 value for field 'ID' (tag=1): %w", err)
			} else {
				m.ID = csproto.Int32(v)
			}
		case 2: // TheString (string,optional)
			if wt != csproto.WireTypeLengthDelimited {
				return fmt.Errorf("incorrect wire type %v for field 'theString' (tag=2), expected 2 (length-delimited)", wt)
			}
			if s, err := dec.DecodeString(); err != nil {
				return fmt.Errorf("unable to decode string value for field 'theString' (tag=2): %w", err)
			} else {
				m.TheString = csproto.String(s)
			}

		case 3: // TheBool (bool,optional)
			if wt != csproto.WireTypeVarint {
				return fmt.Errorf("incorrect wire type %v for tag field 'theBool' (tag=3), expected 0 (varint)", wt)
			}
			if v, err := dec.DecodeBool(); err != nil {
				return fmt.Errorf("unable to decode boolean value for field 'theBool' (tag=3): %w", err)
			} else {
				m.TheBool = csproto.Bool(v)
			}
		case 4: // TheInt32 (int32,optional)
			if wt != csproto.WireTypeVarint {
				return fmt.Errorf("incorrect wire type %v for tag field 'theInt32' (tag=4), expected 0 (varint)", wt)
			}
			if v, err := dec.DecodeInt32(); err != nil {
				return fmt.Errorf("unable to decode int32 value for field 'theInt32' (tag=4): %w", err)
			} else {
				m.TheInt32 = csproto.Int32(v)
			}
		case 5: // TheInt64 (int64,optional)
			if wt != csproto.WireTypeVarint {
				return fmt.Errorf("incorrect wire type %v for tag field 'theInt64' (tag=5), expected 0 (varint)", wt)
			}
			if v, err := dec.DecodeInt64(); err != nil {
				return fmt.Errorf("unable to decode int64 value for field 'theInt64' (tag=5): %w", err)
			} else {
				m.TheInt64 = csproto.Int64(v)
			}
		case 6: // TheUInt32 (uint32,optional)
			if wt != csproto.WireTypeVarint {
				return fmt.Errorf("incorrect wire type %v for tag field 'theUInt32' (tag=6), expected 0 (varint)", wt)
			}
			if v, err := dec.DecodeUInt32(); err != nil {
				return fmt.Errorf("unable to decode int32 value for field 'theUInt32' (tag=6): %w", err)
			} else {
				m.TheUInt32 = csproto.Uint32(v)
			}
		case 7: // TheUInt64 (uint64,optional)
			if wt != csproto.WireTypeVarint {
				return fmt.Errorf("incorrect wire type %v for tag field 'theUInt64' (tag=7), expected 0 (varint)", wt)
			}
			if v, err := dec.DecodeUInt64(); err != nil {
				return fmt.Errorf("unable to decode uint64 value for field 'theUInt64' (tag=7): %w", err)
			} else {
				m.TheUInt64 = csproto.Uint64(v)
			}
		case 8: // TheSInt32 (sint32,optional)
			if wt != csproto.WireTypeVarint {
				return fmt.Errorf("incorrect wire type %v for tag field 'theSInt32' (tag=8), expected 0 (varint)", wt)
			}
			if v, err := dec.DecodeSInt32(); err != nil {
				return fmt.Errorf("unable to decode sint32 value for field 'theSInt32' (tag=8): %w", err)
			} else {
				m.TheSInt32 = csproto.Int32(v)
			}
		case 9: // TheSInt64 (sint64,optional)
			if wt != csproto.WireTypeVarint {
				return fmt.Errorf("incorrect wire type %v for tag field 'theSInt64' (tag=9), expected 0 (varint)", wt)
			}
			if v, err := dec.DecodeSInt64(); err != nil {
				return fmt.Errorf("unable to decode sint64 value for field 'theSInt64' (tag=9): %w", err)
			} else {
				m.TheSInt64 = csproto.Int64(v)
			}
		case 10: // TheFixed32 (fixed32,optional)
			if wt != csproto.WireTypeFixed32 {
				return fmt.Errorf("incorrect wire type %v for tag field 'theFixed32' (tag=10), expected 5 (32-bit)", wt)
			}
			if v, err := dec.DecodeFixed32(); err != nil {
				return fmt.Errorf("unable to decode uint32 value for field 'theFixed32' (tag=10): %w", err)
			} else {
				m.TheFixed32 = csproto.Uint32(v)
			}
		case 11: // TheFixed64 (fixed64,optional)
			if wt != csproto.WireTypeFixed64 {
				return fmt.Errorf("incorrect wire type %v for tag field 'theFixed64' (tag=11), expected 1 (64-bit)", wt)
			}
			if v, err := dec.DecodeFixed64(); err != nil {
				return fmt.Errorf("unable to decode uint64 value for field 'theFixed64' (tag=11): %w", err)
			} else {
				m.TheFixed64 = csproto.Uint64(v)
			}
		case 12: // TheSFixed32 (sfixed32,optional)
			if wt != csproto.WireTypeFixed32 {
				return fmt.Errorf("incorrect wire type %v for field 'theSFixed32' (tag=12), expected 5 (32-bit)", wt)
			}
			if v, err := dec.DecodeFixed32(); err != nil {
				return fmt.Errorf("unable to decode sfixed32 value for field 'theSFixed32' (tag=12): %w", err)
			} else {
				iv := int32(v)
				m.TheSFixed32 = &iv
			}

		case 13: // TheSFixed64 (sfixed64,optional)
			if wt != csproto.WireTypeFixed64 {
				return fmt.Errorf("incorrect wire type %v for field 'theSFixed64' (tag=13), expected 1 (64-bit)", wt)
			}
			if v, err := dec.DecodeFixed64(); err != nil {
				return fmt.Errorf("unable to decode sfixed64 value for field 'theSFixed64' (tag=13): %w", err)
			} else {
				iv := int64(v)
				m.TheSFixed64 = &iv
			}

		case 14: // TheFloat (float,optional)
			if wt != csproto.WireTypeFixed32 {
				return fmt.Errorf("incorrect wire type %v for tag field 'theFloat' (tag=14), expected 5 (32-bit)", wt)
			}
			if v, err := dec.DecodeFloat32(); err != nil {
				return fmt.Errorf("unable to decode float value for field 'theFloat' (tag=14): %w", err)
			} else {
				m.TheFloat = csproto.Float32(v)
			}
		case 15: // TheDouble (double,optional)
			if wt != csproto.WireTypeFixed64 {
				return fmt.Errorf("incorrect wire type %v for tag field 'theDouble' (tag=15), expected 1 (64-bit)", wt)
			}
			if v, err := dec.DecodeFloat64(); err != nil {
				return fmt.Errorf("unable to decode double value for field 'theDouble' (tag=15): %w", err)
			} else {
				m.TheDouble = csproto.Float64(v)
			}
		case 16: // TheEventType (enum,optional)
			if wt != csproto.WireTypeVarint {
				return fmt.Errorf("incorrect wire type %v for tag field 'theEventType' (tag=16), expected 0 (varint)", wt)
			}
			if v, err := dec.DecodeInt32(); err != nil {
				return fmt.Errorf("unable to decode int32 enum value for field 'theEventType' (tag=16): %w", err)
			} else {
				ev := EventType(v)
				m.TheEventType = &ev
			}
		case 17: // TheBytes (bytes,optional)

			if wt != csproto.WireTypeLengthDelimited {
				return fmt.Errorf("incorrect wire type %v for field 'theBytes' (tag=17), expected 2 (length-delimited)", wt)
			}
			if b, err := dec.DecodeBytes(); err != nil {
				return fmt.Errorf("unable to decode bytes value for field 'theBytes' (tag=17): %w", err)
			} else {
				m.TheBytes = b
			}

		case 18: // TheMessage (message,optional)
			if wt != csproto.WireTypeLengthDelimited {
				return fmt.Errorf("incorrect wire type %v for field 'theMessage' (tag=18), expected 2 (length-delimited)", wt)
			}
			var mm EmbeddedEvent
			if err = dec.DecodeNested(&mm); err != nil {
				return fmt.Errorf("unable to decode message value for field 'theMessage' (tag=18): %w", err)
			}
			m.TheMessage = &mm

		default:
			if skipped, err := dec.Skip(tag, wt); err != nil {
				return fmt.Errorf("invalid operation skipping tag %v: %w", tag, err)
			} else {
				m.unknownFields = append(m.unknownFields, skipped...)
			}
		}
	}
	// verify required fields are assigned
	if err := m.csprotoCheckRequiredFields(); err != nil {
		return err
	}

	return nil
}

// csprotoCheckRequiredFields is called by Unmarshal() to ensure that all required fields have been
// populated.
func (m *AllTheThings) csprotoCheckRequiredFields() error {
	var missingFields []string

	if m.ID == nil {
		missingFields = append(missingFields, "ID")
	}

	if len(missingFields) > 0 {
		var sb strings.Builder
		sb.WriteString("cannot unmarshal, one or more required fields missing: ")
		for i, s := range missingFields {
			if i > 0 {
				sb.WriteRune(',')
			}
			sb.WriteString(s)
		}
		return fmt.Errorf(sb.String())
	}
	return nil
}

//------------------------------------------------------------------------------
// Custom Protobuf size/marshal/unmarshal code for RepeatAllTheThings

// Size calculates and returns the size, in bytes, required to hold the contents of m using the Protobuf
// binary encoding.
func (m *RepeatAllTheThings) Size() int {
	if m == nil {
		return 0
	}
	var sz, l int
	_ = l // avoid unused variable

	// ID (int32,required)
	if m.ID != nil {
		sz += csproto.SizeOfTagKey(1) + csproto.SizeOfVarint(uint64(*m.ID))
	}
	// TheStrings (string,repeated)
	for _, sv := range m.TheStrings {
		l = len(sv)
		sz += csproto.SizeOfTagKey(2) + csproto.SizeOfVarint(uint64(l)) + l
	}
	// TheBools (bool,repeated)
	if n := len(m.TheBools); n > 0 {
		sz += csproto.SizeOfTagKey(3) + n
	}
	// TheInt32S (int32,repeated)
	for _, iv := range m.TheInt32S {
		sz += csproto.SizeOfTagKey(4) + csproto.SizeOfVarint(uint64(iv))
	}
	// TheInt64S (int64,repeated)
	for _, iv := range m.TheInt64S {
		sz += csproto.SizeOfTagKey(5) + csproto.SizeOfVarint(uint64(iv))
	}
	// TheUInt32S (uint32,repeated)
	for _, iv := range m.TheUInt32S {
		sz += csproto.SizeOfTagKey(6) + csproto.SizeOfVarint(uint64(iv))
	}
	// TheUInt64S (uint64,repeated)
	for _, iv := range m.TheUInt64S {
		sz += csproto.SizeOfTagKey(7) + csproto.SizeOfVarint(uint64(iv))
	}
	// TheSInt32S (sint32,repeated)
	for _, val := range m.TheSInt32S {
		sz += csproto.SizeOfTagKey(8) + csproto.SizeOfZigZag(uint64(val))
	}
	// TheSInt64S (sint64,repeated)
	for _, val := range m.TheSInt64S {
		sz += csproto.SizeOfTagKey(9) + csproto.SizeOfZigZag(uint64(val))
	}
	// TheFixed32S (fixed32,repeated)
	if l = len(m.TheFixed32S); l > 0 {
		sz += l * (csproto.SizeOfTagKey(10) + 4)
	}
	// TheFixed64S (fixed64,repeated)
	if l = len(m.TheFixed64S); l > 0 {
		sz += l * (csproto.SizeOfTagKey(11) + 8)
	}
	// TheSFixed32S (sfixed32,repeated)
	if l = len(m.TheSFixed32S); l > 0 {
		sz += l * (csproto.SizeOfTagKey(12) + 4)
	}
	// TheSFixed64S (sfixed64,repeated)
	if l = len(m.TheSFixed64S); l > 0 {
		sz += l * (csproto.SizeOfTagKey(13) + 8)
	}
	// TheFloats (float,repeated)
	if l = len(m.TheFloats); l > 0 {
		sz += l * (csproto.SizeOfTagKey(14) + 4)
	}
	// TheDoubles (double,repeated)
	if l = len(m.TheDoubles); l > 0 {
		sz += l * (csproto.SizeOfTagKey(15) + 8)
	}
	// TheEventTypes (enum,repeated)
	for _, iv := range m.TheEventTypes {
		sz += csproto.SizeOfTagKey(16) + csproto.SizeOfVarint(uint64(iv))
	}
	// TheBytes (bytes,repeated)
	for _, bv := range m.TheBytes {
		if l = len(bv); l > 0 {
			sz += csproto.SizeOfTagKey(17) + csproto.SizeOfVarint(uint64(l)) + l
		}
	}
	// TheMessages (message,repeated)
	for _, val := range m.TheMessages {
		if l = csproto.Size(val); l > 0 {
			sz += csproto.SizeOfTagKey(18) + csproto.SizeOfVarint(uint64(l)) + l
		}
	}
	return sz
}

// Marshal converts the contents of m to the Protobuf binary encoding and returns the result or an error.
func (m *RepeatAllTheThings) Marshal() ([]byte, error) {
	siz := m.Size()
	buf := make([]byte, siz)
	err := m.MarshalTo(buf)
	return buf, err
}

// MarshalTo converts the contents of m to the Protobuf binary encoding and writes the result to dest.
func (m *RepeatAllTheThings) MarshalTo(dest []byte) error {
	var (
		enc    = csproto.NewEncoder(dest)
		buf    []byte
		err    error
		extVal interface{}
	)
	// ensure no unused variables
	_ = enc
	_ = buf
	_ = err
	_ = extVal

	// ID (1,int32,required)
	if m.ID == nil {
		return fmt.Errorf("required field 'ID' has no value")
	}
	enc.EncodeInt32(1, *m.ID)
	// TheStrings (2,string,repeated)
	for _, val := range m.TheStrings {
		enc.EncodeString(2, val)
	}
	// TheBools (3,bool,repeated)
	for _, val := range m.TheBools {
		enc.EncodeBool(3, val)
	}
	// TheInt32S (4,int32,repeated)
	for _, val := range m.TheInt32S {
		enc.EncodeInt32(4, val)
	}
	// TheInt64S (5,int64,repeated)
	for _, val := range m.TheInt64S {
		enc.EncodeInt64(5, val)
	}
	// TheUInt32S (6,uint32,repeated)
	for _, val := range m.TheUInt32S {
		enc.EncodeUInt32(6, val)
	}
	// TheUInt64S (7,uint64,repeated)
	for _, val := range m.TheUInt64S {
		enc.EncodeUInt64(7, val)
	}
	// TheSInt32S (8,sint32,repeated)
	for _, val := range m.TheSInt32S {
		enc.EncodeSInt32(8, val)
	}
	// TheSInt64S (9,sint64,repeated)
	for _, val := range m.TheSInt64S {
		enc.EncodeSInt64(9, val)
	}
	// TheFixed32S (10,fixed32,repeated)
	for _, val := range m.TheFixed32S {
		enc.EncodeFixed32(10, val)
	}
	// TheFixed64S (11,fixed64,repeated)
	for _, val := range m.TheFixed64S {
		enc.EncodeFixed64(11, val)
	}
	// TheSFixed32S (12,sfixed32,repeated)
	for _, val := range m.TheSFixed32S {
		enc.EncodeFixed32(12, uint32(val))
	}
	// TheSFixed64S (13,sfixed64,repeated)
	for _, val := range m.TheSFixed64S {
		enc.EncodeFixed64(13, uint64(val))
	}
	// TheFloats (14,float,repeated)
	for _, val := range m.TheFloats {
		enc.EncodeFloat32(14, val)
	}
	// TheDoubles (15,double,repeated)
	for _, val := range m.TheDoubles {
		enc.EncodeFloat64(15, val)
	}
	// TheEventTypes (16,enum,repeated)
	for _, v := range m.TheEventTypes {
		enc.EncodeInt32(16, int32(v))
	}
	// TheBytes (17,bytes,repeated)
	for _, val := range m.TheBytes {
		enc.EncodeBytes(17, val)
	}
	// TheMessages (18,message,repeated)
	for _, mm := range m.TheMessages {
		if err = enc.EncodeNested(18, mm); err != nil {
			return fmt.Errorf("unable to encode message data for field 'theMessages' (tag=18): %w", err)
		}
	}
	return nil
}

// Unmarshal decodes a binary encoded Protobuf message from p and populates m with the result.
func (m *RepeatAllTheThings) Unmarshal(p []byte) error {
	if len(p) == 0 {
		return fmt.Errorf("cannot unmarshal from an empty buffer")
	}
	// clear any existing data
	m.Reset()
	dec := csproto.NewDecoder(p)
	for dec.More() {
		tag, wt, err := dec.DecodeTag()
		if err != nil {
			return err
		}
		switch tag {
		case 1: // ID (int32,required)
			if wt != csproto.WireTypeVarint {
				return fmt.Errorf("incorrect wire type %v for tag field 'ID' (tag=1), expected 0 (varint)", wt)
			}
			if v, err := dec.DecodeInt32(); err != nil {
				return fmt.Errorf("unable to decode int32 value for field 'ID' (tag=1): %w", err)
			} else {
				m.ID = csproto.Int32(v)
			}
		case 2: // TheStrings (string,repeated)
			if wt != csproto.WireTypeLengthDelimited {
				return fmt.Errorf("incorrect wire type %v for field 'theStrings' (tag=2), expected 2 (length-delimited)", wt)
			}
			if s, err := dec.DecodeString(); err != nil {
				return fmt.Errorf("unable to decode string value for field 'theStrings' (tag=2): %w", err)
			} else {
				m.TheStrings = append(m.TheStrings, s)
			}

		case 3: // TheBools (bool,repeated)
			switch wt {
			case csproto.WireTypeVarint:
				if v, err := dec.DecodeBool(); err != nil {
					return fmt.Errorf("unable to decode boolean value for field 'theBools' (tag=3): %w", err)
				} else {
					m.TheBools = append(m.TheBools, v)
				}
			case csproto.WireTypeLengthDelimited:
				if v, err := dec.DecodePackedBool(); err != nil {
					return fmt.Errorf("unable to decode packed boolean values for field 'theBools' (tag=3): %w", err)
				} else {
					m.TheBools = append(m.TheBools, v...)
				}
			default:
				return fmt.Errorf("incorrect wire type %v for repeated field 'theBools' (tag=3), expected 0 (varint) or 1 (length-delimited)", wt)
			}
		case 4: // TheInt32S (int32,repeated)
			switch wt {
			case csproto.WireTypeVarint:
				if v, err := dec.DecodeInt32(); err != nil {
					return fmt.Errorf("unable to decode int32 value for field 'theInt32s' (tag=4): %w", err)
				} else {
					m.TheInt32S = append(m.TheInt32S, v)
				}
			case csproto.WireTypeLengthDelimited:
				if v, err := dec.DecodePackedInt32(); err != nil {
					return fmt.Errorf("unable to decode packed int32 values for field 'theInt32s' (tag=4): %w", err)
				} else {
					m.TheInt32S = append(m.TheInt32S, v...)
				}
			default:
				return fmt.Errorf("incorrect wire type %v for repeated field 'theInt32s' (tag=4), expected 0 (varint) or 1 (length-delimited)", wt)
			}
		case 5: // TheInt64S (int64,repeated)
			switch wt {
			case csproto.WireTypeVarint:
				if v, err := dec.DecodeInt64(); err != nil {
					return fmt.Errorf("unable to decode int64 value for field 'theInt64s' (tag=5): %w", err)
				} else {
					m.TheInt64S = append(m.TheInt64S, v)
				}
			case csproto.WireTypeLengthDelimited:
				if v, err := dec.DecodePackedInt64(); err != nil {
					return fmt.Errorf("unable to decode packed int64 values for field 'theInt64s' (tag=5): %w", err)
				} else {
					m.TheInt64S = append(m.TheInt64S, v...)
				}
			default:
				return fmt.Errorf("incorrect wire type %v for repeated field 'theInt64s' (tag=5), expected 0 (varint) or 1 (length-delimited)", wt)
			}
		case 6: // TheUInt32S (uint32,repeated)
			switch wt {
			case csproto.WireTypeVarint:
				if v, err := dec.DecodeUInt32(); err != nil {
					return fmt.Errorf("unable to decode uint32 value for field 'theUInt32s' (tag=6): %w", err)
				} else {
					m.TheUInt32S = append(m.TheUInt32S, v)
				}
			case csproto.WireTypeLengthDelimited:
				if v, err := dec.DecodePackedUint32(); err != nil {
					return fmt.Errorf("unable to decode packed uint32 values for field 'theUInt32s' (tag=6): %w", err)
				} else {
					m.TheUInt32S = append(m.TheUInt32S, v...)
				}
			default:
				return fmt.Errorf("incorrect wire type %v for repeated field 'theUInt32s' (tag=6), expected 0 (varint) or 1 (length-delimited)", wt)
			}
		case 7: // TheUInt64S (uint64,repeated)
			switch wt {
			case csproto.WireTypeVarint:
				if v, err := dec.DecodeUInt64(); err != nil {
					return fmt.Errorf("unable to decode uint64 value for field 'theUInt64s' (tag=7): %w", err)
				} else {
					m.TheUInt64S = append(m.TheUInt64S, v)
				}
			case csproto.WireTypeLengthDelimited:
				if v, err := dec.DecodePackedUint64(); err != nil {
					return fmt.Errorf("unable to decode packed uint64 values for field 'theUInt64s' (tag=7): %w", err)
				} else {
					m.TheUInt64S = append(m.TheUInt64S, v...)
				}
			default:
				return fmt.Errorf("incorrect wire type %v for repeated field 'theUInt64s' (tag=7), expected 0 (varint) or 1 (length-delimited)", wt)
			}
		case 8: // TheSInt32S (sint32,repeated)
			switch wt {
			case csproto.WireTypeVarint:
				if v, err := dec.DecodeSInt32(); err != nil {
					return fmt.Errorf("unable to decode sint32 value for field 'theSInt32s' (tag=8): %w", err)
				} else {
					m.TheSInt32S = append(m.TheSInt32S, v)
				}
			case csproto.WireTypeLengthDelimited:
				if v, err := dec.DecodePackedSint32(); err != nil {
					return fmt.Errorf("unable to decode packed sint32 values for field 'theSInt32s' (tag=8): %w", err)
				} else {
					m.TheSInt32S = append(m.TheSInt32S, v...)
				}
			default:
				return fmt.Errorf("incorrect wire type %v for repeated field 'theSInt32s' (tag=8), expected 0 (varint) or 1 (length-delimited)", wt)
			}
		case 9: // TheSInt64S (sint64,repeated)
			switch wt {
			case csproto.WireTypeVarint:
				if v, err := dec.DecodeSInt64(); err != nil {
					return fmt.Errorf("unable to decode sint64 value for field 'theSInt64s' (tag=9): %w", err)
				} else {
					m.TheSInt64S = append(m.TheSInt64S, v)
				}
			case csproto.WireTypeLengthDelimited:
				if v, err := dec.DecodePackedSint64(); err != nil {
					return fmt.Errorf("unable to decode packed sint64 values for field 'theSInt64s' (tag=9): %w", err)
				} else {
					m.TheSInt64S = append(m.TheSInt64S, v...)
				}
			default:
				return fmt.Errorf("incorrect wire type %v for repeated field 'theSInt64s' (tag=9), expected 0 (varint) or 1 (length-delimited)", wt)
			}
		case 10: // TheFixed32S (fixed32,repeated)
			switch wt {
			case csproto.WireTypeFixed32:
				if v, err := dec.DecodeFixed32(); err != nil {
					return fmt.Errorf("unable to decode uint32 value for field 'theFixed32s' (tag=10): %w", err)
				} else {
					m.TheFixed32S = append(m.TheFixed32S, v)
				}
			case csproto.WireTypeLengthDelimited:
				if v, err := dec.DecodePackedFixed32(); err != nil {
					return fmt.Errorf("unable to decode packed uint32 values for field 'theFixed32s' (tag=10): %w", err)
				} else {
					m.TheFixed32S = append(m.TheFixed32S, v...)
				}
			default:
				return fmt.Errorf("incorrect wire type %v for repeated field 'theFixed32s' (tag=10), expected 5 (32-bit) or 1 (length-delimited)", wt)
			}
		case 11: // TheFixed64S (fixed64,repeated)
			switch wt {
			case csproto.WireTypeFixed64:
				if v, err := dec.DecodeFixed64(); err != nil {
					return fmt.Errorf("unable to decode uint64 value for field 'theFixed64s' (tag=11): %w", err)
				} else {
					m.TheFixed64S = append(m.TheFixed64S, v)
				}
			case csproto.WireTypeLengthDelimited:
				if v, err := dec.DecodePackedFixed64(); err != nil {
					return fmt.Errorf("unable to decode packed uint64 values for field 'theFixed64s' (tag=11): %w", err)
				} else {
					m.TheFixed64S = append(m.TheFixed64S, v...)
				}
			default:
				return fmt.Errorf("incorrect wire type %v for repeated field 'theFixed64s' (tag=11), expected 1 (64-bit) or 1 (length-delimited)", wt)
			}
		case 12: // TheSFixed32S (sfixed32,repeated)
			if wt != csproto.WireTypeFixed32 {
				return fmt.Errorf("incorrect wire type %v for field 'theSFixed32s' (tag=12), expected 5 (32-bit)", wt)
			}
			if v, err := dec.DecodeFixed32(); err != nil {
				return fmt.Errorf("unable to decode sfixed32 value for field 'theSFixed32s' (tag=12): %w", err)
			} else {
				m.TheSFixed32S = append(m.TheSFixed32S, int32(v))
			}

		case 13: // TheSFixed64S (sfixed64,repeated)
			if wt != csproto.WireTypeFixed64 {
				return fmt.Errorf("incorrect wire type %v for field 'theSFixed64s' (tag=13), expected 1 (64-bit)", wt)
			}
			if v, err := dec.DecodeFixed64(); err != nil {
				return fmt.Errorf("unable to decode sfixed64 value for field 'theSFixed64s' (tag=13): %w", err)
			} else {
				m.TheSFixed64S = append(m.TheSFixed64S, int64(v))
			}

		case 14: // TheFloats (float,repeated)
			switch wt {
			case csproto.WireTypeFixed32:
				if v, err := dec.DecodeFloat32(); err != nil {
					return fmt.Errorf("unable to decode float value for field 'theFloats' (tag=14): %w", err)
				} else {
					m.TheFloats = append(m.TheFloats, v)
				}
			case csproto.WireTypeLengthDelimited:
				if v, err := dec.DecodePackedFloat32(); err != nil {
					return fmt.Errorf("unable to decode packed float values for field 'theFloats' (tag=14): %w", err)
				} else {
					m.TheFloats = append(m.TheFloats, v...)
				}
			default:
				return fmt.Errorf("incorrect wire type %v for repeated field 'theFloats' (tag=14), expected 5 (32-bit) or 1 (length-delimited)", wt)
			}
		case 15: // TheDoubles (double,repeated)
			switch wt {
			case csproto.WireTypeFixed64:
				if v, err := dec.DecodeFloat64(); err != nil {
					return fmt.Errorf("unable to decode double value for field 'theDoubles' (tag=15): %w", err)
				} else {
					m.TheDoubles = append(m.TheDoubles, v)
				}
			case csproto.WireTypeLengthDelimited:
				if v, err := dec.DecodePackedFloat64(); err != nil {
					return fmt.Errorf("unable to decode packed double values for field 'theDoubles' (tag=15): %w", err)
				} else {
					m.TheDoubles = append(m.TheDoubles, v...)
				}
			default:
				return fmt.Errorf("incorrect wire type %v for repeated field 'theDoubles' (tag=15), expected 1 (64-bit) or 1 (length-delimited)", wt)
			}
		case 16: // TheEventTypes (enum,repeated)
			switch wt {
			case csproto.WireTypeVarint:
				if v, err := dec.DecodeInt32(); err != nil {
					return fmt.Errorf("unable to decode int32 enum value for field 'theEventTypes' (tag=16): %w", err)
				} else {
					m.TheEventTypes = append(m.TheEventTypes, EventType(v))
				}
			case csproto.WireTypeLengthDelimited:
				if v, err := dec.DecodePackedInt32(); err != nil {
					return fmt.Errorf("unable to decode packed int32 enum values for field 'theEventTypes' (tag=16): %w", err)
				} else {
					for _, elem := range v {
						m.TheEventTypes = append(m.TheEventTypes, EventType(elem))
					}
				}
			default:
				return fmt.Errorf("incorrect wire type %v for repeated field 'theEventTypes' (tag=16), expected 0 (varint) or 1 (length-delimited)", wt)
			}
		case 17: // TheBytes (bytes,repeated)

			if wt != csproto.WireTypeLengthDelimited {
				return fmt.Errorf("incorrect wire type %v for field 'theBytes' (tag=17), expected 2 (length-delimited)", wt)
			}
			if b, err := dec.DecodeBytes(); err != nil {
				return fmt.Errorf("unable to decode bytes value for field 'theBytes' (tag=17): %w", err)
			} else {
				m.TheBytes = append(m.TheBytes, b)
			}

		case 18: // TheMessages (message,repeated)
			if wt != csproto.WireTypeLengthDelimited {
				return fmt.Errorf("incorrect wire type %v for field 'theMessages' (tag=18), expected 2 (length-delimited)", wt)
			}
			var mm EmbeddedEvent
			if err = dec.DecodeNested(&mm); err != nil {
				return fmt.Errorf("unable to decode message value for field 'theMessages' (tag=18): %w", err)
			}
			m.TheMessages = append(m.TheMessages, &mm)

		default:
			if skipped, err := dec.Skip(tag, wt); err != nil {
				return fmt.Errorf("invalid operation skipping tag %v: %w", tag, err)
			} else {
				m.unknownFields = append(m.unknownFields, skipped...)
			}
		}
	}
	// verify required fields are assigned
	if err := m.csprotoCheckRequiredFields(); err != nil {
		return err
	}

	return nil
}

// csprotoCheckRequiredFields is called by Unmarshal() to ensure that all required fields have been
// populated.
func (m *RepeatAllTheThings) csprotoCheckRequiredFields() error {
	var missingFields []string

	if m.ID == nil {
		missingFields = append(missingFields, "ID")
	}

	if len(missingFields) > 0 {
		var sb strings.Builder
		sb.WriteString("cannot unmarshal, one or more required fields missing: ")
		for i, s := range missingFields {
			if i > 0 {
				sb.WriteRune(',')
			}
			sb.WriteString(s)
		}
		return fmt.Errorf(sb.String())
	}
	return nil
}

//------------------------------------------------------------------------------
// Custom Protobuf size/marshal/unmarshal code for TestEvent_NestedMsg

// Size calculates and returns the size, in bytes, required to hold the contents of m using the Protobuf
// binary encoding.
func (m *TestEvent_NestedMsg) Size() int {
	if m == nil {
		return 0
	}
	var sz, l int
	_ = l // avoid unused variable

	// Details (string,optional)
	if m.Details != nil {
		l = len(*m.Details)
		sz += csproto.SizeOfTagKey(1) + csproto.SizeOfVarint(uint64(l)) + l
	}
	return sz
}

// Marshal converts the contents of m to the Protobuf binary encoding and returns the result or an error.
func (m *TestEvent_NestedMsg) Marshal() ([]byte, error) {
	siz := m.Size()
	buf := make([]byte, siz)
	err := m.MarshalTo(buf)
	return buf, err
}

// MarshalTo converts the contents of m to the Protobuf binary encoding and writes the result to dest.
func (m *TestEvent_NestedMsg) MarshalTo(dest []byte) error {
	var (
		enc    = csproto.NewEncoder(dest)
		buf    []byte
		err    error
		extVal interface{}
	)
	// ensure no unused variables
	_ = enc
	_ = buf
	_ = err
	_ = extVal

	// Details (1,string,optional)
	if m.Details != nil {
		enc.EncodeString(1, *m.Details)
	}
	return nil
}

// Unmarshal decodes a binary encoded Protobuf message from p and populates m with the result.
func (m *TestEvent_NestedMsg) Unmarshal(p []byte) error {
	if len(p) == 0 {
		return fmt.Errorf("cannot unmarshal from an empty buffer")
	}
	// clear any existing data
	m.Reset()
	dec := csproto.NewDecoder(p)
	for dec.More() {
		tag, wt, err := dec.DecodeTag()
		if err != nil {
			return err
		}
		switch tag {
		case 1: // Details (string,optional)
			if wt != csproto.WireTypeLengthDelimited {
				return fmt.Errorf("incorrect wire type %v for field 'details' (tag=1), expected 2 (length-delimited)", wt)
			}
			if s, err := dec.DecodeString(); err != nil {
				return fmt.Errorf("unable to decode string value for field 'details' (tag=1): %w", err)
			} else {
				m.Details = csproto.String(s)
			}

		default:
			if skipped, err := dec.Skip(tag, wt); err != nil {
				return fmt.Errorf("invalid operation skipping tag %v: %w", tag, err)
			} else {
				m.unknownFields = append(m.unknownFields, skipped...)
			}
		}
	}
	return nil
}
